#!/usr/bin/env python3
import copy
import json
import random
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"

MECHANIC_PATH = ROOT / "evolution/walk_mechanic_xioi_v1.json"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

AGENT_LUA_PATH = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
RESULT_PATH = TORIBASH_SCRIPT_DIR / "toribashai_episode_result.json"

POP_DIR = ROOT / "evolution/population_xioi_mechanic_v7"
BEST_DIR = ROOT / "evolution/best_xioi_mechanic_v7"
CHAMPION_PATH = ROOT / "evolution/champion_xioi_mechanic_v7.json"

POP_SIZE = 10
GENERATIONS = 999999

MUTATION_RATE = 0.012
MUTATION_VALUES = [1, 2, 3, 4]

# jambes uniquement
MUTABLE_JOINTS = {4, 5, 6, 7, 14, 15, 16, 17, 18, 19}

# bras / torse / cou protégés
PROTECTED_JOINTS = {0, 1, 2, 3, 8, 9, 10, 11, 12, 13}

RESET_COMMAND = "/reset"


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2), encoding="utf-8")


def clamp_state(v):
    v = int(v)
    if v < 1:
        return 3
    if v > 4:
        return 4
    return v


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by evolution_loop_xioi_mechanic_v7.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append(f"TORIBASHAI_AGENT.loop_length = {agent.get('loop_length', 428)}")
    lines.append("TORIBASHAI_AGENT.commands = {")

    for cmd in agent["commands"]:
        pairs = ", ".join(
            f"{{{int(j)}, {clamp_state(v)}}}"
            for j, v in cmd["pairs"]
        )
        lines.append(f"    {{ frame = {int(cmd['frame'])}, joints = {{ {pairs} }} }},")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    AGENT_LUA_PATH.write_text("\n".join(lines), encoding="utf-8")


def reset_toribash_clipboard():
    try:
        subprocess.run(
            ["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"],
            check=False,
        )
        time.sleep(0.10)

        subprocess.run(["wl-copy"], input=RESET_COMMAND.encode("utf-8"), check=False)

        subprocess.run(["xdotool", "key", "t"], check=False)
        time.sleep(0.08)
        subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
        time.sleep(0.03)
        subprocess.run(["xdotool", "key", "BackSpace"], check=False)
        time.sleep(0.03)
        subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
        time.sleep(0.03)
        subprocess.run(["xdotool", "key", "Return"], check=False)

        # Lance le match automatiquement
        time.sleep(0.20)
        subprocess.run(["xdotool", "key", "space"], check=False)

        print("Reset + space envoyés")
    except Exception as e:
        print("Reset clipboard erreur:", e)


def wait_result(timeout=45):
    start = time.time()

    while time.time() - start < timeout:
        if RESULT_PATH.exists():
            try:
                result = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return result
            except Exception:
                pass

        time.sleep(0.25)

    return {
        "score": -999999,
        "reason": "timeout",
        "x": 0,
        "y": 0,
        "z": 0,
        "final_dist": 999,
        "progress_y": 0,
        "fell": True,
        "frames": 0,
    }


def mutate_agent(agent):
    child = copy.deepcopy(agent)
    mutations = 0

    for cmd in child["commands"]:
        for pair in cmd["pairs"]:
            joint = int(pair[0])

            if joint in PROTECTED_JOINTS:
                continue

            if joint not in MUTABLE_JOINTS:
                continue

            if random.random() < MUTATION_RATE:
                current = clamp_state(pair[1])
                choices = [v for v in MUTATION_VALUES if v != current]
                pair[1] = random.choice(choices)
                mutations += 1

    child["mutations"] = mutations
    child["mutation_rate"] = MUTATION_RATE
    child["mutation_policy"] = "legs_only_xioi_mechanic_locked"

    return child


def eliminate_bad_behavior(result):
    z = float(result.get("z", 999))
    progress_y = float(result.get("progress_y", 0))
    x = float(result.get("x", 0))
    fell = bool(result.get("fell", False))

    if fell:
        return True, "fell"

    # Plongeon / levier : avance mais corps bas.
    if progress_y > 2.5 and z < 5.6:
        return True, "dive_or_arm_lever"

    # Trop de dérive latérale.
    if abs(x) > 8.0:
        return True, "side_drift"

    # Corps beaucoup trop bas même sans fell.
    if z < 4.8:
        return True, "too_low"

    return False, ""


def evaluate(agent, gen, idx):
    agent_name = f"xioi_v7_gen_{gen:05d}_agent_{idx:03d}"
    agent["name"] = agent_name

    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_lua(agent)

    print("Exported:", AGENT_LUA_PATH)
    print("Source:", path)
    print("Agent:", agent_name)
    print("Commands:", len(agent["commands"]))
    print("Mutations:", agent.get("mutations", 0))

    reset_toribash_clipboard()

    print("Attente :", RESULT_PATH)
    result = wait_result()

    score = float(result.get("score", -999999))

    bad, reason = eliminate_bad_behavior(result)
    if bad:
        score = -999999
        result["eliminated"] = True
        result["elimination_reason"] = reason
        print("ÉLIMINÉ:", reason)

    result["score_after_elimination"] = score

    result_path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json"
    save_json(result_path, result)

    return score, result, path


def main():
    random.seed()

    POP_DIR.mkdir(parents=True, exist_ok=True)
    BEST_DIR.mkdir(parents=True, exist_ok=True)

    mechanic = load_json(MECHANIC_PATH)

    if CHAMPION_PATH.exists():
        champion = load_json(CHAMPION_PATH)
        print("Champion existant chargé:", CHAMPION_PATH)
    else:
        champion = {
            "name": "xioi_mechanic_seed",
            "source_mechanic": str(MECHANIC_PATH),
            "loop_length": mechanic["loop_length"],
            "commands": mechanic["commands"],
        }
        save_json(CHAMPION_PATH, champion)
        print("Seed mechanic chargé:", MECHANIC_PATH)

    champion_score = -999999

    print()
    print("=" * 49)
    print("INIT MANUEL TORIBASH")
    print("=" * 49)
    print("Dans Toribash, lance une seule fois :")
    print("/lm toribashai_goal_flat_v1.tbm")
    print("/ls toribash_reward_runner_v13_7.lua")
    input("\nQuand c'est prêt, appuie Entrée ici... ")

    for gen in range(GENERATIONS):
        print()
        print("=" * 49)
        print(f"GENERATION {gen}")
        print("=" * 49)

        candidates = []

        for i in range(POP_SIZE):
            if i == 0:
                candidate = copy.deepcopy(champion)
                candidate["mutations"] = 0
                candidate["elite_copy"] = True
            else:
                candidate = mutate_agent(champion)
                candidate["elite_copy"] = False

            candidates.append(candidate)

        best_score = -999999
        best_path = None
        best_result = None

        for i, candidate in enumerate(candidates):
            print()
            print("=" * 49)
            print(f"GEN {gen} | CANDIDAT {i:03d}")
            print("=" * 49)

            score, result, path = evaluate(candidate, gen, i)

            print()
            print(f"CANDIDAT {i:03d}")
            print(f"SCORE = {score:.4f}")
            print(result)

            if score > best_score:
                best_score = score
                best_path = path
                best_result = result

        print()
        print("=" * 49)
        print("MEILLEUR CANDIDAT")
        print("=" * 49)
        print("Score :", best_score)
        print("Fichier :", best_path)

        if best_score > champion_score and best_path is not None:
            champion_score = best_score
            champion = load_json(best_path)

            champion_save = BEST_DIR / f"champion_gen_{gen:05d}_score_{champion_score:.2f}.json"
            save_json(champion_save, champion)
            shutil.copy(champion_save, CHAMPION_PATH)

            print()
            print("NOUVEAU CHAMPION")
            print(champion_save)
        else:
            print()
            print("Pas mieux que le champion actuel")

        state = {
            "generation": gen,
            "champion_score": champion_score,
            "champion_path": str(CHAMPION_PATH),
            "best_score_this_gen": best_score,
            "best_result_this_gen": best_result,
            "mutation_rate": MUTATION_RATE,
            "policy": "xioi_mechanic_locked_legs_only",
        }
        save_json(ROOT / "evolution/xioi_mechanic_v7_state.json", state)


if __name__ == "__main__":
    main()
