#!/usr/bin/env python3
import json
import re
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"

RPL = ROOT / "replays_raw/parkour_candidate/#Xioi#Pk - YpSkA.rpl"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
OUT_JSON = ROOT / "evolution" / "xioi_rpl_command_agent.json"

MAX_FRAME = 427
LOOP_COUNT = 4

FRAME_RE = re.compile(r"^FRAME\s+(\d+);")
JOINT_RE = re.compile(r"^JOINT\s+0;\s*(.*)$")


def fix(v):
    v = int(v)
    if v < 1:
        return 3
    if v > 4:
        return 4
    return v


def parse_rpl_commands():
    current_frame = None
    commands = []

    for line in RPL.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()

        m = FRAME_RE.match(line)
        if m:
            current_frame = int(m.group(1))
            continue

        m = JOINT_RE.match(line)
        if m and current_frame is not None and current_frame <= MAX_FRAME:
            nums = [int(x) for x in m.group(1).split()]
            pairs = []

            for i in range(0, len(nums) - 1, 2):
                joint = int(nums[i])
                value = fix(nums[i + 1])
                pairs.append([joint, value])

            commands.append({
                "frame": current_frame,
                "pairs": pairs,
            })

    return commands


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by generate_xioi_rpl_command_agent.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append(f"TORIBASHAI_AGENT.loop_length = {agent['loop_length']}")
    lines.append("TORIBASHAI_AGENT.commands = {")

    for cmd in agent["commands"]:
        pairs = ", ".join(f"{{{j}, {v}}}" for j, v in cmd["pairs"])
        lines.append(f"    {{ frame = {cmd['frame']}, joints = {{ {pairs} }} }},")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    OUT_LUA.write_text("\n".join(lines), encoding="utf-8")


def main():
    base = parse_rpl_commands()

    if not base:
        raise RuntimeError("Aucune commande JOINT trouvée.")

    loop_length = MAX_FRAME + 1
    commands = []

    for loop in range(LOOP_COUNT):
        offset = loop * loop_length
        for cmd in base:
            commands.append({
                "frame": cmd["frame"] + offset,
                "pairs": cmd["pairs"],
            })

    agent = {
        "name": "xioi_rpl_command_clone_loop",
        "source": str(RPL),
        "max_frame": MAX_FRAME,
        "loop_count": LOOP_COUNT,
        "loop_length": loop_length,
        "base_commands": len(base),
        "commands": commands,
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    OUT_JSON.write_text(json.dumps(agent, indent=2), encoding="utf-8")
    export_lua(agent)

    print("RPL command agent exporté")
    print("Base commands:", len(base))
    print("Total commands:", len(commands))
    print("JSON:", OUT_JSON)
    print("Lua :", OUT_LUA)
    print("First:", base[0])
    print("Last :", base[-1])


if __name__ == "__main__":
    main()
