#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"

SOURCE = ROOT / "parsed/#Xioi#Pk - YpSkA.json"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
OUT_JSON = ROOT / "evolution" / "walk_xioi_gold_direct_current.json"

PLAYER_ID = "0"
MAX_FRAME = 427

CONTROL_JOINTS = [
    4, 5, 6, 7,
    14, 15, 16,
    17, 18, 19,
]


def fix_joint_state(v):
    v = int(v)
    if v <= 0:
        return 3
    if v > 4:
        return 4
    return v


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by generate_xioi_gold_direct_agent.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append("TORIBASHAI_AGENT.control_joints = { 4, 5, 6, 7, 14, 15, 16, 17, 18, 19 }")
    lines.append("TORIBASHAI_AGENT.actions = {")

    for action in agent["actions"]:
        values = ", ".join(str(int(v)) for v in action)
        lines.append(f"    {{ {values} }},")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    OUT_LUA.write_text("\n".join(lines), encoding="utf-8")


def main():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    frames = data["frames"]

    frame_ids = sorted(
        int(k) for k in frames.keys()
        if int(k) <= MAX_FRAME
    )

    actions = []

    for fid in frame_ids:
        frame = frames[str(fid)]
        player = frame.get("players", {}).get(PLAYER_ID)

        if not player:
            continue

        joints = player.get("joints", {})

        action = []
        for j in CONTROL_JOINTS:
            action.append(fix_joint_state(joints.get(str(j), 3)))

        actions.append(action)

    agent = {
        "name": "xioi_gold_direct_until_427",
        "source": str(SOURCE),
        "max_frame": MAX_FRAME,
        "control_joints": CONTROL_JOINTS,
        "actions": actions,
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    OUT_JSON.write_text(json.dumps(agent, indent=2), encoding="utf-8")
    export_lua(agent)

    print("Agent Xioi direct exporté")
    print("JSON:", OUT_JSON)
    print("Lua :", OUT_LUA)
    print("Actions:", len(actions))
    print("Première action:", actions[0])
    print("Dernière action:", actions[-1])


if __name__ == "__main__":
    main()
