#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"

SOURCE = ROOT / "parsed/#Xioi#Pk - YpSkA.json"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
OUT_JSON = ROOT / "evolution" / "walk_xioi_infinite_current.json"

PLAYER_ID = "0"

START_FRAME = 0
END_FRAME = 427

# Le replay assassincreedhunter est en turnframes 5.
FRAME_STEP = 5

# Longueur exportée. 300 turns = très long, mais cyclique.
NUM_TURNS = 300

# Full body : jambes + torse + bras + cou.
CONTROL_JOINTS = list(range(20))


def fix_state(v):
    v = int(v)
    if v <= 0:
        return 3
    if v > 4:
        return 4
    return v


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by generate_xioi_infinite_walk_agent.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append(
        "TORIBASHAI_AGENT.control_joints = { "
        + ", ".join(str(j) for j in agent["control_joints"])
        + " }"
    )
    lines.append("TORIBASHAI_AGENT.actions = {")

    for action in agent["actions"]:
        values = ", ".join(str(int(v)) for v in action)
        lines.append(f"    {{ {values} }},")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    OUT_LUA.write_text("\n".join(lines), encoding="utf-8")


def main():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    frames = data["frames"]

    available = sorted(int(k) for k in frames.keys())
    usable = [
        f for f in available
        if START_FRAME <= f <= END_FRAME and (f - START_FRAME) % FRAME_STEP == 0
    ]

    if not usable:
        raise RuntimeError("Aucune frame utilisable.")

    base_actions = []

    for fid in usable:
        frame = frames[str(fid)]
        player = frame.get("players", {}).get(PLAYER_ID)
        if not player:
            continue

        joints = player.get("joints", {})

        action = []
        for j in CONTROL_JOINTS:
            action.append(fix_state(joints.get(str(j), 3)))

        base_actions.append(action)

    if not base_actions:
        raise RuntimeError("Aucune action trouvée.")

    actions = []
    for i in range(NUM_TURNS):
        actions.append(base_actions[i % len(base_actions)])

    agent = {
        "name": "xioi_infinite_walk_loop",
        "source": str(SOURCE),
        "start_frame": START_FRAME,
        "end_frame": END_FRAME,
        "frame_step": FRAME_STEP,
        "base_cycle_len": len(base_actions),
        "num_turns": NUM_TURNS,
        "control_joints": CONTROL_JOINTS,
        "actions": actions,
        "locked_style": "xioi_walk_loop",
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    OUT_JSON.write_text(json.dumps(agent, indent=2), encoding="utf-8")
    export_lua(agent)

    print("Agent Xioi infinite exporté")
    print("Base cycle:", len(base_actions))
    print("Turns:", len(actions))
    print("JSON:", OUT_JSON)
    print("Lua :", OUT_LUA)
    print("First:", actions[0])
    print("Last :", actions[-1])


if __name__ == "__main__":
    main()
