#!/usr/bin/env python3
import json
import math
from pathlib import Path

import torch
import torch.nn as nn

ROOT = Path.home() / "Documents" / "ToribashAI"

MODEL_PATH = ROOT / "models/xioi_motion_clone_v1.pt"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
OUT_JSON = ROOT / "evolution" / "xioi_motion_clone_agent_v1.json"

MAX_FRAME = 427
NUM_CLASSES = 5
ACTION_DIM = 20
HIDDEN = 256

LOOP_COUNT = 4


class MotionMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(7, HIDDEN),
            nn.GELU(),
            nn.Linear(HIDDEN, HIDDEN),
            nn.GELU(),
            nn.Linear(HIDDEN, HIDDEN),
            nn.GELU(),
            nn.Linear(HIDDEN, ACTION_DIM * NUM_CLASSES),
        )

    def forward(self, x):
        return self.net(x).view(-1, ACTION_DIM, NUM_CLASSES)


def make_x(fid):
    t = fid / MAX_FRAME
    return [
        t,
        math.sin(t * math.pi * 2),
        math.cos(t * math.pi * 2),
        math.sin(t * math.pi * 4),
        math.cos(t * math.pi * 4),
        math.sin(t * math.pi * 8),
        math.cos(t * math.pi * 8),
    ]


def fix_toribash(v):
    v = int(v)
    if v <= 0:
        return 3
    if v > 4:
        return 4
    return v


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by generate_xioi_motion_clone_agent_v1.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append(
        "TORIBASHAI_AGENT.control_joints = { "
        + ", ".join(str(j) for j in agent["control_joints"])
        + " }"
    )
    lines.append("TORIBASHAI_AGENT.actions = {")

    for action in agent["actions"]:
        values = ", ".join(str(int(v)) for v in action)
        lines.append(f"    {{ {values} }},")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    OUT_LUA.write_text("\n".join(lines), encoding="utf-8")


def main():
    ckpt = torch.load(MODEL_PATH, map_location="cpu")

    model = MotionMLP()
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    frame_ids = ckpt.get("frame_ids", list(range(MAX_FRAME + 1)))

    base_actions = []

    with torch.no_grad():
        for fid in frame_ids:
            x = torch.tensor([make_x(fid)], dtype=torch.float32)
            logits = model(x)
            pred = logits.argmax(dim=-1)[0].tolist()
            pred = [fix_toribash(v) for v in pred]
            base_actions.append(pred)

    actions = []
    for _ in range(LOOP_COUNT):
        actions.extend(base_actions)

    agent = {
        "name": "xioi_motion_clone_v1_looped",
        "source_model": str(MODEL_PATH),
        "max_frame": MAX_FRAME,
        "base_cycle_len": len(base_actions),
        "loop_count": LOOP_COUNT,
        "control_joints": list(range(ACTION_DIM)),
        "actions": actions,
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    OUT_JSON.write_text(json.dumps(agent, indent=2), encoding="utf-8")
    export_lua(agent)

    print("Agent clone exporté")
    print("Base cycle:", len(base_actions))
    print("Total actions:", len(actions))
    print("JSON:", OUT_JSON)
    print("Lua :", OUT_LUA)
    print("First:", actions[0])


if __name__ == "__main__":
    main()
