#!/usr/bin/env python3
import copy
import json
import random
import re
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"
SCRIPTS = ROOT / "scripts"
EVOLUTION = ROOT / "evolution"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

LUA_NAME = "toribash_walk_gru_live_runner_v3.lua"
PROJECT_LUA = SCRIPTS / LUA_NAME
STEAM_LUA = TORIBASH_SCRIPT_DIR / LUA_NAME

AGENT_LUA = TORIBASH_SCRIPT_DIR / "toribash_walk_gru_live_agent_v3.lua"
RESULT_PATH = TORIBASH_SCRIPT_DIR / "toribash_walk_gru_live_result_v3.json"

SEED_RPL = ROOT / "generated_replays/xioi_loop_len265_gru_long_v54_seed048_template_safe.rpl"
FALLBACK_RPL = ROOT / "generated_replays/xioi_loop_len265_champion_v51.rpl"

SEED_AGENT = EVOLUTION / "walk_gru_live_seed_v3.json"
CHAMPION_AGENT = EVOLUTION / "walk_gru_live_champion_v3.json"
POP_DIR = EVOLUTION / "population_walk_gru_live_v3"
BEST_DIR = EVOLUTION / "best_walk_gru_live_v3"
STATE_PATH = EVOLUTION / "walk_gru_live_v3_state.json"

POP_SIZE = 10
GENERATIONS = 999999
JOINT_VALUES = [1, 2, 3, 4]

# Frame-indexed actions. First part is preserved because it contains the launch.
PROTECTED_UNTIL_FRAME = 315
BASE_MUTATION_RATE = 0.010
EARLY_LOOP_MUTATION_RATE = 0.004
NO_CHANGE_BIAS = 0.45
RESET_COMMAND = "/lm Urban_Structure/assassincreedhunter.tbm"

FRAME_RE = re.compile(r"^FRAME\s+(-?\d+)\s*;")
JOINT_RE = re.compile(r"^JOINT\s+0\s*;\s*(.*)$")


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2), encoding="utf-8")


def parse_joint_pairs(rest):
    nums = [int(x) for x in re.findall(r"-?\d+", rest)]
    pairs = []
    for i in range(0, len(nums) - 1, 2):
        j, v = nums[i], nums[i + 1]
        if 0 <= j <= 19 and 1 <= v <= 4:
            pairs.append([j, v])
    return pairs


def extract_actions_from_rpl(path):
    if not path.exists():
        raise FileNotFoundError(path)
    actions = []
    current_frame = None
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        m = FRAME_RE.match(raw.strip())
        if m:
            current_frame = int(m.group(1))
            continue
        jm = JOINT_RE.match(raw.strip())
        if jm and current_frame is not None:
            pairs = parse_joint_pairs(jm.group(1))
            if pairs:
                actions.append({"frame": current_frame, "pairs": pairs})
    # merge duplicate frame JOINTs
    by_frame = {}
    for a in actions:
        by_frame.setdefault(a["frame"], {})
        for j, v in a["pairs"]:
            by_frame[a["frame"]][j] = v
    merged = []
    for fr in sorted(by_frame):
        merged.append({"frame": fr, "pairs": [[j, by_frame[fr][j]] for j in sorted(by_frame[fr])]})
    return merged


def infer_loop(actions):
    frames = [a["frame"] for a in actions]
    max_frame = max(frames) if frames else 0
    # For V54 seed048, this is already a long template-safe walk. Use full extracted timeline.
    return max(5, max_frame + 5)


def make_seed_agent():
    source = SEED_RPL if SEED_RPL.exists() else FALLBACK_RPL
    actions = extract_actions_from_rpl(source)
    if not actions:
        raise RuntimeError(f"No JOINT actions extracted from {source}")
    agent = {
        "name": "walk_gru_live_seed_v3",
        "branch": "walk_gru_live",
        "version": 3,
        "source_rpl": str(source),
        "generation": 0,
        "agent_index": 0,
        "protected_until_frame": PROTECTED_UNTIL_FRAME,
        "loop_start_frame": 0,
        "loop_length": infer_loop(actions),
        "actions": actions,
        "mutation_rate": BASE_MUTATION_RATE,
    }
    return agent


def lua_quote(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def export_agent_lua(agent):
    lines = []
    lines.append("-- Auto-generated by evolution_loop_walk_gru_live_v3.py")
    lines.append("TORIBASHAI_WALK_AGENT = {}")
    lines.append(f'TORIBASHAI_WALK_AGENT.name = "{lua_quote(agent.get("name", "walk_agent"))}"')
    lines.append(f'TORIBASHAI_WALK_AGENT.generation = {int(agent.get("generation", 0))}')
    lines.append(f'TORIBASHAI_WALK_AGENT.agent_index = {int(agent.get("agent_index", 0))}')
    lines.append(f'TORIBASHAI_WALK_AGENT.loop_start_frame = {int(agent.get("loop_start_frame", 0))}')
    lines.append(f'TORIBASHAI_WALK_AGENT.loop_length = {int(agent.get("loop_length", 0))}')
    lines.append("TORIBASHAI_WALK_AGENT.actions = {")
    for a in agent.get("actions", []):
        pairs = a.get("pairs", [])
        pair_chunks = []
        for j, v in pairs:
            pair_chunks.append("{" + f"{int(j)}, {int(v)}" + "}")
        lines.append("  { frame = " + str(int(a.get("frame", 0))) + ", pairs = { " + ", ".join(pair_chunks) + " } },")
    lines.append("}")
    lines.append("TORIBASHAI_AGENT = TORIBASHAI_WALK_AGENT")
    lines.append("return TORIBASHAI_WALK_AGENT")
    AGENT_LUA.write_text("\n".join(lines) + "\n", encoding="utf-8")


def mutation_rate_for_frame(fr):
    if fr < PROTECTED_UNTIL_FRAME:
        return 0.0
    if fr < PROTECTED_UNTIL_FRAME + 180:
        return EARLY_LOOP_MUTATION_RATE
    return BASE_MUTATION_RATE


def mutate(agent):
    child = copy.deepcopy(agent)
    mutations = 0
    for a in child.get("actions", []):
        fr = int(a.get("frame", 0))
        rate = mutation_rate_for_frame(fr)
        if rate <= 0:
            continue
        for pair in a.get("pairs", []):
            if random.random() < rate:
                cur = int(pair[1])
                if random.random() < NO_CHANGE_BIAS:
                    new = 3
                else:
                    choices = [v for v in JOINT_VALUES if v != cur]
                    new = random.choice(choices)
                if new != cur:
                    pair[1] = new
                    mutations += 1
    child["mutations"] = mutations
    child["mutation_rate"] = BASE_MUTATION_RATE
    child["protected_until_frame"] = PROTECTED_UNTIL_FRAME
    return child


def reset_toribash():
    try:
        subprocess.run(["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"], check=False)
        time.sleep(0.10)
        try:
            p = subprocess.Popen(["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE)
            p.communicate(RESET_COMMAND.encode("utf-8"))
            subprocess.run(["xdotool", "key", "t"], check=False)
            time.sleep(0.07)
            subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
            time.sleep(0.02)
            subprocess.run(["xdotool", "key", "BackSpace"], check=False)
            time.sleep(0.02)
            subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
            time.sleep(0.02)
            subprocess.run(["xdotool", "key", "Return"], check=False)
            time.sleep(0.15)
            # Auto-space faster after reset.
            subprocess.run(["xdotool", "key", "space"], check=False)
        except Exception:
            subprocess.run(["xdotool", "key", "t"], check=False)
            time.sleep(0.07)
            subprocess.run(["xdotool", "type", "--delay", "1", RESET_COMMAND], check=False)
            subprocess.run(["xdotool", "key", "Return"], check=False)
            time.sleep(0.15)
            subprocess.run(["xdotool", "key", "space"], check=False)
    except Exception as e:
        print("Reset error:", e)


def wait_result(timeout=95):
    start = time.time()
    while time.time() - start < timeout:
        if RESULT_PATH.exists():
            try:
                result = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return result
            except Exception:
                pass
        time.sleep(0.25)
    return {"score": -999999, "reason": "timeout", "frames": 0}


def setup():
    EVOLUTION.mkdir(parents=True, exist_ok=True)
    POP_DIR.mkdir(parents=True, exist_ok=True)
    BEST_DIR.mkdir(parents=True, exist_ok=True)
    if not PROJECT_LUA.exists():
        raise FileNotFoundError(f"Missing Lua in scripts: {PROJECT_LUA}")
    shutil.copy2(PROJECT_LUA, STEAM_LUA)
    seed = make_seed_agent()
    save_json(SEED_AGENT, seed)
    if not CHAMPION_AGENT.exists():
        save_json(CHAMPION_AGENT, seed)
    export_agent_lua(seed)
    print("Lua copied:", STEAM_LUA)
    print("Seed actions:", len(seed["actions"]))
    print("Seed source:", seed["source_rpl"])
    print("Agent exported:", AGENT_LUA)
    print("In Toribash load:")
    print("  ls toribash_walk_gru_live_runner_v3.lua")


def evaluate(agent, gen, idx):
    agent = copy.deepcopy(agent)
    agent["generation"] = gen
    agent["agent_index"] = idx
    agent["name"] = f"walk_gru_live_v3_gen_{gen:05d}_agent_{idx:03d}"
    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_agent_lua(agent)
    RESULT_PATH.unlink(missing_ok=True)
    print("Agent:", agent["name"], "mutations:", agent.get("mutations", 0))
    reset_toribash()
    result = wait_result()
    score = float(result.get("score", -999999))
    save_json(POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json", result)
    print("SCORE", score, result)
    return score, result, path


def one_gen():
    if PROJECT_LUA.exists():
        shutil.copy2(PROJECT_LUA, STEAM_LUA)
    if not CHAMPION_AGENT.exists():
        setup()
    champion = load_json(CHAMPION_AGENT)
    state = load_json(STATE_PATH) if STATE_PATH.exists() else {"generation": 0, "champion_score": -999999}
    gen = int(state.get("generation", 0))
    champion_score = float(state.get("champion_score", -999999))

    candidates = []
    for i in range(POP_SIZE):
        if i == 0:
            c = copy.deepcopy(champion)
            c["mutations"] = 0
            c["elite_copy"] = True
        else:
            c = mutate(champion)
            c["elite_copy"] = False
        candidates.append(c)

    best_score = -999999
    best_result = None
    best_path = None
    for i, c in enumerate(candidates):
        print("\n" + "=" * 50)
        print(f"GEN {gen} | AGENT {i:03d}")
        print("=" * 50)
        score, result, path = evaluate(c, gen, i)
        if score > best_score:
            best_score = score
            best_result = result
            best_path = path

    if best_score > champion_score:
        champion_score = best_score
        champion = load_json(best_path)
        BEST_DIR.mkdir(parents=True, exist_ok=True)
        champ_save = BEST_DIR / f"champion_gen_{gen:05d}_score_{champion_score:.2f}.json"
        save_json(champ_save, champion)
        shutil.copy2(champ_save, CHAMPION_AGENT)
        print("NEW CHAMPION:", champ_save)
    else:
        print("No new champion")

    save_json(STATE_PATH, {
        "generation": gen + 1,
        "champion_score": champion_score,
        "best_score_this_gen": best_score,
        "best_result_this_gen": best_result,
        "champion_path": str(CHAMPION_AGENT),
        "seed_source": str(SEED_RPL if SEED_RPL.exists() else FALLBACK_RPL),
        "mutation_rate": BASE_MUTATION_RATE,
        "protected_until_frame": PROTECTED_UNTIL_FRAME,
    })


def run_forever():
    while True:
        one_gen()


def main():
    import sys
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    if cmd == "setup":
        setup()
    elif cmd == "one-gen":
        one_gen()
    elif cmd == "run":
        run_forever()
    else:
        print("Usage:")
        print("  python3 scripts/evolution_loop_walk_gru_live_v3.py setup")
        print("  python3 scripts/evolution_loop_walk_gru_live_v3.py one-gen")
        print("  python3 scripts/evolution_loop_walk_gru_live_v3.py run")


if __name__ == "__main__":
    main()
