#!/usr/bin/env python3
import copy
import json
import random
import re
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"
SCRIPTS = ROOT / "scripts"
EVOLUTION = ROOT / "evolution"
TORIBASH_SCRIPT_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"

LUA_NAME = "toribash_walk_gru_live_v5.lua"
PROJECT_LUA = SCRIPTS / LUA_NAME
STEAM_LUA = TORIBASH_SCRIPT_DIR / LUA_NAME

AGENT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
RESULT_PATH = TORIBASH_SCRIPT_DIR / "toribash_walk_gru_live_result_v5.json"

# Use the best long template-safe walk as action source, but export it as a live agent.
SEED_RPL = ROOT / "generated_replays/xioi_loop_len265_gru_long_v54_seed048_template_safe.rpl"
FALLBACK_RPLS = [
    ROOT / "generated_replays/xioi_loop_len265_gru_v53_free_template_safe.rpl",
    ROOT / "generated_replays/xioi_loop_len265_champion_v51.rpl",
    ROOT / "generated_replays/xioi_427_assassincreedhunter_v37.rpl",
]

SEED_AGENT = EVOLUTION / "walk_gru_live_seed_v5.json"
CHAMPION_AGENT = EVOLUTION / "walk_gru_live_champion_v5.json"
POP_DIR = EVOLUTION / "population_walk_gru_live_v5"
BEST_DIR = EVOLUTION / "best_walk_gru_live_v5"
STATE_PATH = EVOLUTION / "walk_gru_live_v5_state.json"

POP_SIZE = 10
GENERATIONS = 999999
JOINTS = list(range(20))
JOINT_VALUES = [0, 1, 2, 3, 4]
FRAMES_PER_ACTION = 5
MAX_FRAMES = 1200
PROTECTED_UNTIL_FRAME = 315
BASE_MUTATION_RATE = 0.006
LOOP_MUTATION_RATE = 0.010
NO_CHANGE_BIAS = 0.70
RESET_COMMAND = "/lm ToribashAI/toribashai_xioi_city_v1.tbm"

FRAME_RE = re.compile(r"^FRAME\s+(-?\d+)\s*;")
JOINT0_RE = re.compile(r"^JOINT\s+0\s*;\s*(.*)$")


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2), encoding="utf-8")


def parse_pairs(rest):
    nums = [int(x) for x in re.findall(r"-?\d+", rest)]
    pairs = []
    for i in range(0, len(nums) - 1, 2):
        j, v = nums[i], nums[i + 1]
        if 0 <= j <= 19 and 1 <= v <= 4:
            pairs.append((j, v))
    return pairs


def choose_seed_rpl():
    if SEED_RPL.exists():
        return SEED_RPL
    for p in FALLBACK_RPLS:
        if p.exists():
            return p
    raise FileNotFoundError("No walk GRU template-safe RPL found. Expected V54/V53/V51 outputs.")


def extract_action_vectors_from_rpl(path):
    current_frame = None
    by_frame = {}
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        m = FRAME_RE.match(line)
        if m:
            current_frame = int(m.group(1))
            continue
        jm = JOINT0_RE.match(line)
        if jm and current_frame is not None:
            by_frame.setdefault(current_frame, {})
            for j, v in parse_pairs(jm.group(1)):
                by_frame[current_frame][j] = v
    actions = []
    for fr in sorted(by_frame):
        vec = [0] * 20
        for j, v in by_frame[fr].items():
            vec[j] = int(v)
        if any(v > 0 for v in vec):
            actions.append({"frame": fr, "values": vec})
    return actions


def build_seed_agent():
    source = choose_seed_rpl()
    raw_actions = extract_action_vectors_from_rpl(source)
    if not raw_actions:
        raise RuntimeError(f"No JOINT 0 actions extracted from {source}")

    # Keep action order, but use compact live timing every 5 frames. The original RPL frame
    # numbers are kept only to choose loop/protection boundaries.
    actions = [a["values"] for a in raw_actions]
    protected_actions = 0
    for a in raw_actions:
        if a["frame"] <= PROTECTED_UNTIL_FRAME:
            protected_actions += 1

    # If the source begins directly in a loop, protect less but still keep enough setup.
    if protected_actions < 8:
        protected_actions = min(24, len(actions))

    agent = {
        "name": "walk_gru_live_seed_v5",
        "branch": "walk_gru_live",
        "version": 5,
        "source_rpl": str(source),
        "generation": 0,
        "agent_index": 0,
        "control_joints": JOINTS,
        "actions": actions,
        "frames_per_action": FRAMES_PER_ACTION,
        "max_frames": MAX_FRAMES,
        "protected_actions": protected_actions,
        "loop_start_action": max(1, protected_actions + 1),
        "protected_until_frame": PROTECTED_UNTIL_FRAME,
        "mutation_rate": BASE_MUTATION_RATE,
    }
    return agent


def lua_quote(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def export_agent_lua(agent):
    lines = [
        "-- Auto-generated by evolution_loop_walk_gru_live_v5.py",
        "TORIBASHAI_AGENT = {}",
        f'TORIBASHAI_AGENT.name = "{lua_quote(agent.get("name", "walk_gru_live"))}"',
        f'TORIBASHAI_AGENT.generation = {int(agent.get("generation", 0))}',
        f'TORIBASHAI_AGENT.agent_index = {int(agent.get("agent_index", 0))}',
        f'TORIBASHAI_AGENT.frames_per_action = {int(agent.get("frames_per_action", FRAMES_PER_ACTION))}',
        f'TORIBASHAI_AGENT.max_frames = {int(agent.get("max_frames", MAX_FRAMES))}',
        f'TORIBASHAI_AGENT.protected_actions = {int(agent.get("protected_actions", 1))}',
        f'TORIBASHAI_AGENT.loop_start_action = {int(agent.get("loop_start_action", 1))}',
        "TORIBASHAI_AGENT.control_joints = {" + ", ".join(str(j) for j in agent.get("control_joints", JOINTS)) + "}",
        "TORIBASHAI_AGENT.actions = {",
    ]
    for action in agent.get("actions", []):
        lines.append("    {" + ", ".join(str(int(v)) for v in action) + "},")
    lines += ["}", "return TORIBASHAI_AGENT", ""]
    AGENT_LUA.write_text("\n".join(lines), encoding="utf-8")


def setup():
    if not PROJECT_LUA.exists():
        raise FileNotFoundError(f"Missing Lua in scripts: {PROJECT_LUA}")
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(PROJECT_LUA, STEAM_LUA)
    print("Lua copied:", STEAM_LUA)

    agent = build_seed_agent()
    save_json(SEED_AGENT, agent)
    if not CHAMPION_AGENT.exists():
        save_json(CHAMPION_AGENT, agent)
    export_agent_lua(load_json(CHAMPION_AGENT))
    print("Seed actions:", len(agent["actions"]))
    print("Protected actions:", agent["protected_actions"])
    print("Loop starts at action:", agent["loop_start_action"])
    print("Seed source:", agent["source_rpl"])
    print("Agent exported:", AGENT_LUA)


def reset_toribash():
    try:
        subprocess.run(["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"], check=False)
        time.sleep(0.10)
        try:
            p = subprocess.Popen(["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE)
            p.communicate(RESET_COMMAND.encode("utf-8"))
            subprocess.run(["xdotool", "key", "t"], check=False)
            time.sleep(0.05)
            subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
            time.sleep(0.02)
            subprocess.run(["xdotool", "key", "BackSpace"], check=False)
            time.sleep(0.02)
            subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
            time.sleep(0.02)
            subprocess.run(["xdotool", "key", "Return"], check=False)
        except Exception:
            subprocess.run(["xdotool", "key", "t"], check=False)
            time.sleep(0.05)
            subprocess.run(["xdotool", "type", "--delay", "1", RESET_COMMAND], check=False)
            subprocess.run(["xdotool", "key", "Return"], check=False)
        time.sleep(0.35)
        subprocess.run(["xdotool", "key", "space"], check=False)
        print("Reset + auto-space:", RESET_COMMAND)
    except Exception as e:
        print("Reset error:", e)


def wait_result(timeout=75):
    start = time.time()
    while time.time() - start < timeout:
        if RESULT_PATH.exists():
            try:
                result = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return result
            except Exception:
                pass
        time.sleep(0.20)
    return {"score": -999999, "reason": "timeout", "frames": 0, "fell": True}


def mutation_rate_for_index(i, agent):
    protected = int(agent.get("protected_actions", 0))
    if i < protected:
        return 0.0
    if i < protected + 30:
        return BASE_MUTATION_RATE * 0.35
    return LOOP_MUTATION_RATE


def mutate(agent):
    child = copy.deepcopy(agent)
    mutations = 0
    for ai, action in enumerate(child.get("actions", [])):
        rate = mutation_rate_for_index(ai, child)
        for ji, current in enumerate(action):
            if random.random() < rate:
                if random.random() < NO_CHANGE_BIAS:
                    new_value = 0
                else:
                    choices = [v for v in JOINT_VALUES if v != int(current)]
                    new_value = random.choice(choices)
                action[ji] = int(new_value)
                mutations += 1
    child["mutations"] = mutations
    child["mutation_rate"] = LOOP_MUTATION_RATE
    child["mutation_strategy"] = "v5_protect_launch_mutate_loop_only"
    return child


def evaluate(agent, gen, idx):
    agent = copy.deepcopy(agent)
    agent["generation"] = gen
    agent["agent_index"] = idx
    agent["name"] = f"walk_gru_live_v5_gen_{gen:05d}_agent_{idx:03d}"
    POP_DIR.mkdir(parents=True, exist_ok=True)
    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_agent_lua(agent)

    if RESULT_PATH.exists():
        RESULT_PATH.unlink(missing_ok=True)

    print("\n" + "=" * 52)
    print(f"GEN {gen} | AGENT {idx:03d}")
    print("Source:", path)
    print("Mutations:", agent.get("mutations", 0))
    print("Protected actions:", agent.get("protected_actions"))
    print("Actions:", len(agent.get("actions", [])))
    reset_toribash()
    result = wait_result()
    score = float(result.get("score", -999999))
    save_json(POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json", result)
    print("SCORE:", score)
    print(result)
    return score, result, path


def one_gen():
    if not STEAM_LUA.exists() and PROJECT_LUA.exists():
        shutil.copy2(PROJECT_LUA, STEAM_LUA)
    if not CHAMPION_AGENT.exists():
        setup()
    champion = load_json(CHAMPION_AGENT)
    POP_DIR.mkdir(parents=True, exist_ok=True)
    BEST_DIR.mkdir(parents=True, exist_ok=True)

    state = load_json(STATE_PATH) if STATE_PATH.exists() else {"generation": 0, "champion_score": -999999}
    gen = int(state.get("generation", 0))
    champion_score = float(state.get("champion_score", -999999))

    candidates = []
    for i in range(POP_SIZE):
        if i == 0:
            c = copy.deepcopy(champion)
            c["elite_copy"] = True
            c["mutations"] = 0
        else:
            c = mutate(champion)
            c["elite_copy"] = False
        candidates.append(c)

    best_score = -999999
    best_path = None
    best_result = None
    for i, c in enumerate(candidates):
        score, result, path = evaluate(c, gen, i)
        if score > best_score:
            best_score = score
            best_path = path
            best_result = result

    print("\nBEST THIS GEN", best_score, best_path, best_result)
    if best_score > champion_score:
        new_champ = load_json(best_path)
        save_json(CHAMPION_AGENT, new_champ)
        shutil.copy2(best_path, BEST_DIR / f"champion_gen_{gen:05d}_score_{best_score:.2f}.json")
        champion_score = best_score
        print("NEW CHAMPION")

    save_json(STATE_PATH, {
        "generation": gen + 1,
        "champion_score": champion_score,
        "best_score_this_gen": best_score,
        "best_result_this_gen": best_result,
        "champion": str(CHAMPION_AGENT),
        "mod": RESET_COMMAND,
        "seed": str(SEED_AGENT),
    })


def run_forever():
    while True:
        one_gen()


def main():
    import sys
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    if cmd == "setup":
        setup()
    elif cmd == "one-gen":
        one_gen()
    elif cmd == "run":
        run_forever()
    elif cmd == "reset":
        reset_toribash()
    else:
        print("Usage:")
        print("  python3 scripts/evolution_loop_walk_gru_live_v5.py setup")
        print("  python3 scripts/evolution_loop_walk_gru_live_v5.py one-gen")
        print("  python3 scripts/evolution_loop_walk_gru_live_v5.py run")


if __name__ == "__main__":
    main()
