#!/usr/bin/env python3
# evolution_loop_walk_gru_live_v4.py
# Live evolution for ToribashAI walk_gru branch.
# V4 fixes:
# - correct mod: ToribashAI/toribashai_xioi_city_v1.tbm
# - longer episodes: 1200 frames
# - exports agent as global Lua table + return
# - reset with clipboard and auto-space shortly after reset
# - seed from V54/V53 template-safe RPL actions

import copy
import json
import random
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"
SCRIPTS = ROOT / "scripts"
EVOLUTION = ROOT / "evolution"

TORIBASH_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash"
TORIBASH_SCRIPT_DIR = TORIBASH_DIR / "data/script"

LUA_NAME = "toribash_walk_gru_live_runner_v4.lua"
PROJECT_LUA = SCRIPTS / LUA_NAME
STEAM_LUA = TORIBASH_SCRIPT_DIR / LUA_NAME

AGENT_LUA = TORIBASH_SCRIPT_DIR / "toribash_walk_gru_live_agent_v4.lua"
RESULT_PATH = TORIBASH_SCRIPT_DIR / "toribash_walk_gru_live_result_v4.json"

SEED_AGENT = EVOLUTION / "walk_gru_live_seed_v4.json"
CHAMPION_AGENT = EVOLUTION / "walk_gru_live_champion_v4.json"
STATE_PATH = EVOLUTION / "walk_gru_live_v4_state.json"
POP_DIR = EVOLUTION / "population_walk_gru_live_v4"
BEST_DIR = EVOLUTION / "best_walk_gru_live_v4"

SEED_RPL_CANDIDATES = [
    ROOT / "generated_replays/xioi_loop_len265_gru_long_v54_seed048_template_safe.rpl",
    ROOT / "generated_replays/xioi_loop_len265_gru_v53_free_template_safe.rpl",
    ROOT / "generated_replays/xioi_loop_len265_champion_v51.rpl",
]

POP_SIZE = 10
GENERATIONS = 999999
JOINT_VALUES = [1, 2, 3, 4]
BASE_MUTATION_RATE = 0.018
PROTECTED_FRAME = 315
SOFT_FRAME = 500
SOFT_FACTOR = 0.25
FRAMES_PER_ACTION = 5
MAX_FRAMES = 1200
EARLY_STOP_AFTER = 220
RESET_COMMAND = "/lm ToribashAI/toribashai_xioi_city_v1.tbm"

def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))

def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2), encoding="utf-8")

def parse_joint_pairs(line):
    if ";" not in line:
        return []
    left, right = line.split(";", 1)
    if not left.strip().startswith("JOINT 0"):
        return []
    nums = right.strip().split()
    vals = []
    try:
        ints = [int(float(x)) for x in nums]
    except Exception:
        return []
    for i in range(0, len(ints) - 1, 2):
        j, v = ints[i], ints[i+1]
        if 0 <= j <= 19 and 1 <= v <= 4:
            vals.append([j, v])
    return vals

def extract_actions_from_rpl(path):
    current_frame = None
    actions = []
    merged = {}
    for raw in Path(path).read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if line.startswith("FRAME "):
            try:
                current_frame = int(line.split()[1].replace(";", ""))
            except Exception:
                current_frame = None
        elif current_frame is not None and line.startswith("JOINT 0;"):
            pairs = parse_joint_pairs(line)
            if pairs:
                merged.setdefault(current_frame, {})
                for j, v in pairs:
                    merged[current_frame][int(j)] = int(v)
    for fr in sorted(merged):
        if fr < 0:
            continue
        pairs = [[j, v] for j, v in sorted(merged[fr].items())]
        actions.append({"frame": fr, "pairs": pairs})
    return actions

def lua_quote(s):
    return json.dumps(str(s), ensure_ascii=False)

def export_agent_lua(agent):
    lines = [
        "-- Auto-generated by evolution_loop_walk_gru_live_v4.py",
        "TORIBASH_WALK_GRU_AGENT_V4 = {}",
        f"TORIBASH_WALK_GRU_AGENT_V4.name = {lua_quote(agent.get('name','walk_gru_agent'))}",
        f"TORIBASH_WALK_GRU_AGENT_V4.generation = {int(agent.get('generation', -1))}",
        f"TORIBASH_WALK_GRU_AGENT_V4.candidate = {int(agent.get('candidate', -1))}",
        f"TORIBASH_WALK_GRU_AGENT_V4.frames_per_action = {FRAMES_PER_ACTION}",
        f"TORIBASH_WALK_GRU_AGENT_V4.max_frames = {MAX_FRAMES}",
        f"TORIBASH_WALK_GRU_AGENT_V4.early_stop_after = {EARLY_STOP_AFTER}",
        "TORIBASH_WALK_GRU_AGENT_V4.actions = {",
    ]
    for a in agent["actions"]:
        pairs = a.get("pairs", [])
        pair_txt = ", ".join("{%d,%d}" % (int(j), int(v)) for j, v in pairs)
        lines.append("    { frame = %d, pairs = { %s } }," % (int(a["frame"]), pair_txt))
    lines += [
        "}",
        "TORIBASHAI_AGENT = TORIBASH_WALK_GRU_AGENT_V4",
        "return TORIBASH_WALK_GRU_AGENT_V4",
        "",
    ]
    AGENT_LUA.write_text("\n".join(lines), encoding="utf-8")

def ensure_seed():
    if SEED_AGENT.exists():
        return
    seed_rpl = next((p for p in SEED_RPL_CANDIDATES if p.exists()), None)
    if not seed_rpl:
        raise FileNotFoundError("Missing seed RPL. Expected one of:\n" + "\n".join(map(str, SEED_RPL_CANDIDATES)))
    actions = extract_actions_from_rpl(seed_rpl)
    if not actions:
        raise RuntimeError(f"No JOINT actions extracted from {seed_rpl}")
    agent = {
        "name": "walk_gru_live_seed_v4",
        "source_rpl": str(seed_rpl),
        "frames_per_action": FRAMES_PER_ACTION,
        "max_frames": MAX_FRAMES,
        "protected_frame": PROTECTED_FRAME,
        "actions": actions,
    }
    save_json(SEED_AGENT, agent)
    print("Seed created:", SEED_AGENT)
    print("Seed source:", seed_rpl)
    print("Actions:", len(actions))

def mutation_rate(frame):
    if frame <= PROTECTED_FRAME:
        return 0.0
    if frame <= SOFT_FRAME:
        return BASE_MUTATION_RATE * SOFT_FACTOR
    return BASE_MUTATION_RATE

def mutate(agent):
    child = copy.deepcopy(agent)
    mutations = 0
    for a in child["actions"]:
        fr = int(a["frame"])
        rate = mutation_rate(fr)
        if rate <= 0:
            continue
        new_pairs = []
        for j, v in a.get("pairs", []):
            if random.random() < rate:
                choices = [x for x in JOINT_VALUES if x != int(v)]
                v = random.choice(choices)
                mutations += 1
            new_pairs.append([int(j), int(v)])
        # rare add existing walking joint after soft zone
        if fr > SOFT_FRAME and random.random() < rate * 0.15:
            j = random.choice([1,3,4,5,7,8,12,13,14,15,16,17,18,19])
            v = random.choice(JOINT_VALUES)
            if all(p[0] != j for p in new_pairs):
                new_pairs.append([j, v])
                mutations += 1
        a["pairs"] = sorted(new_pairs)
    child["mutations"] = mutations
    child["mutation_rate"] = BASE_MUTATION_RATE
    return child

def activate_toribash():
    subprocess.run(["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"], check=False)
    time.sleep(0.08)

def send_chat_command(command):
    activate_toribash()
    try:
        p = subprocess.Popen(["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE)
        p.communicate(command.encode("utf-8"))
        subprocess.run(["xdotool", "key", "t"], check=False)
        time.sleep(0.05)
        subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
        time.sleep(0.02)
        subprocess.run(["xdotool", "key", "BackSpace"], check=False)
        time.sleep(0.02)
        subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
        time.sleep(0.02)
        subprocess.run(["xdotool", "key", "Return"], check=False)
    except Exception:
        subprocess.run(["xdotool", "key", "t"], check=False)
        time.sleep(0.05)
        subprocess.run(["xdotool", "type", "--delay", "1", command], check=False)
        subprocess.run(["xdotool", "key", "Return"], check=False)

def reset_and_start():
    RESULT_PATH.unlink(missing_ok=True)
    send_chat_command(RESET_COMMAND)
    time.sleep(0.18)
    send_chat_command("ls " + LUA_NAME)
    time.sleep(0.18)
    activate_toribash()
    subprocess.run(["xdotool", "key", "space"], check=False)
    time.sleep(0.05)
    subprocess.run(["xdotool", "key", "space"], check=False)
    print("Reset/start:", RESET_COMMAND, "| ls", LUA_NAME)

def wait_result(timeout=80):
    start = time.time()
    while time.time() - start < timeout:
        if RESULT_PATH.exists():
            try:
                result = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return result
            except Exception:
                pass
        time.sleep(0.20)
    return {"score": -999999, "reason": "timeout", "frames": 0, "fell": True}

def evaluate(agent, gen, idx):
    agent = copy.deepcopy(agent)
    agent["generation"] = gen
    agent["candidate"] = idx
    agent["name"] = f"walk_gru_live_v4_g{gen:05d}_a{idx:03d}"
    POP_DIR.mkdir(parents=True, exist_ok=True)
    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_agent_lua(agent)
    print("Agent:", agent["name"], "mutations:", agent.get("mutations", 0), "actions:", len(agent["actions"]))
    reset_and_start()
    result = wait_result()
    score = float(result.get("score", -999999))
    save_json(POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json", result)
    return score, result, path

def setup():
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    EVOLUTION.mkdir(parents=True, exist_ok=True)
    if not PROJECT_LUA.exists():
        raise FileNotFoundError(f"Missing Lua in scripts: {PROJECT_LUA}")
    shutil.copy2(PROJECT_LUA, STEAM_LUA)
    ensure_seed()
    if not CHAMPION_AGENT.exists():
        shutil.copy2(SEED_AGENT, CHAMPION_AGENT)
    champion = load_json(CHAMPION_AGENT)
    champion["generation"] = -1
    champion["candidate"] = -1
    champion["name"] = "walk_gru_live_v4_champion"
    export_agent_lua(champion)
    print("Lua copied:", STEAM_LUA)
    print("Champion:", CHAMPION_AGENT)
    print("Agent exported:", AGENT_LUA)
    print("In Toribash run: ls", LUA_NAME)

def one_gen():
    setup()
    champion = load_json(CHAMPION_AGENT)
    gen = int(load_json(STATE_PATH).get("generation", -1) + 1) if STATE_PATH.exists() else 0
    candidates = []
    for i in range(POP_SIZE):
        if i == 0:
            c = copy.deepcopy(champion)
            c["mutations"] = 0
            c["elite_copy"] = True
        else:
            c = mutate(champion)
            c["elite_copy"] = False
        candidates.append(c)

    best_score = -999999
    best_path = None
    best_result = None
    for i, c in enumerate(candidates):
        print("="*60)
        print("GEN", gen, "CANDIDATE", i)
        score, result, path = evaluate(c, gen, i)
        print("SCORE", score, result)
        if score > best_score:
            best_score, best_path, best_result = score, path, result

    BEST_DIR.mkdir(parents=True, exist_ok=True)
    current = load_json(best_path)
    champion_score = float(load_json(STATE_PATH).get("champion_score", -999999)) if STATE_PATH.exists() else -999999
    if best_score > champion_score:
        shutil.copy2(best_path, CHAMPION_AGENT)
        shutil.copy2(best_path, BEST_DIR / f"champion_gen_{gen:05d}_score_{best_score:.2f}.json")
        champion_score = best_score
        print("NEW CHAMPION:", CHAMPION_AGENT)
    save_json(STATE_PATH, {
        "generation": gen,
        "champion_score": champion_score,
        "best_score_this_gen": best_score,
        "best_result_this_gen": best_result,
        "protected_frame": PROTECTED_FRAME,
        "max_frames": MAX_FRAMES,
        "mod": RESET_COMMAND,
    })

def run_forever():
    setup()
    while True:
        one_gen()

def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    if cmd == "setup":
        setup()
    elif cmd in ("one-gen", "one_gen"):
        one_gen()
    elif cmd == "run":
        run_forever()
    else:
        print("Usage:")
        print("  python3 scripts/evolution_loop_walk_gru_live_v4.py setup")
        print("  python3 scripts/evolution_loop_walk_gru_live_v4.py one-gen")
        print("  python3 scripts/evolution_loop_walk_gru_live_v4.py run")

if __name__ == "__main__":
    main()
