#!/usr/bin/env python3
import copy, json, random, shutil, subprocess, time, re
from pathlib import Path

ROOT = Path.home() / "Documents/ToribashAI"
SCRIPTS = ROOT / "scripts"
EVOL = ROOT / "evolution"
STEAM_SCRIPT_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
LUA_NAME = "toribash_walk_gru_live_v6.lua"
PROJECT_LUA = SCRIPTS / LUA_NAME
STEAM_LUA = STEAM_SCRIPT_DIR / LUA_NAME
AGENT_LUA = STEAM_SCRIPT_DIR / "toribashai_agent_current.lua"
RESULT_PATH = STEAM_SCRIPT_DIR / "toribashai_episode_result.json"

SEED_RPL = ROOT / "generated_replays/xioi_loop_len265_gru_long_v54_seed048_template_safe.rpl"
SEED_JSON = EVOL / "walk_gru_live_seed_v6.json"
CHAMPION_JSON = EVOL / "walk_gru_live_champion_v6.json"
POP_DIR = EVOL / "population_walk_gru_live_v6"
BEST_DIR = EVOL / "best_walk_gru_live_v6"

RESET_COMMAND = "/lm ToribashAI/toribashai_xioi_city_v1.tbm"
POP_SIZE = 10
GENERATIONS = 999999
FRAMES_PER_ACTION = 5
MAX_FRAMES = 1200
PROTECTED_ACTIONS = 64  # ~0..315 frames
BASE_MUT_RATE = 0.018
LOOP_MUT_RATE = 0.026
NO_CHANGE_BIAS = 0.65
JOINT_VALUES = [1,2,3,4]
CONTROL_JOINTS = list(range(20))


def load_json(p):
    return json.loads(Path(p).read_text(encoding="utf-8"))

def save_json(p, obj):
    Path(p).parent.mkdir(parents=True, exist_ok=True)
    Path(p).write_text(json.dumps(obj, indent=2), encoding="utf-8")

def parse_rpl_actions(path):
    actions = []
    current = None
    frame_re = re.compile(r"^FRAME\s+(\d+);")
    joint_re = re.compile(r"^JOINT\s+0;\s*(.*)$")
    for raw in Path(path).read_text(encoding="utf-8", errors="ignore").splitlines():
        m = frame_re.match(raw.strip())
        if m:
            if current is not None:
                actions.append(current)
            current = [0]*20
            continue
        jm = joint_re.match(raw.strip())
        if jm and current is not None:
            nums = [int(x) for x in re.findall(r"-?\d+", jm.group(1))]
            for i in range(0, len(nums)-1, 2):
                j, v = nums[i], nums[i+1]
                if 0 <= j < 20:
                    current[j] = v
    if current is not None:
        actions.append(current)
    return actions

def ensure_seed():
    if SEED_JSON.exists():
        return load_json(SEED_JSON)
    if not SEED_RPL.exists():
        raise FileNotFoundError(f"Missing seed RPL: {SEED_RPL}\nGenerate V54 first.")
    actions = parse_rpl_actions(SEED_RPL)
    if not actions:
        raise RuntimeError(f"No actions extracted from {SEED_RPL}")
    agent = {
        "name": "walk_gru_live_seed_v6",
        "description": "Live agent seeded from xioi len265 GRU/RPL template-safe. Real JSON action prefix then GRU loop.",
        "control_joints": CONTROL_JOINTS,
        "actions": actions,
        "frames_per_action": FRAMES_PER_ACTION,
        "max_frames": MAX_FRAMES,
        "protected_actions": min(PROTECTED_ACTIONS, len(actions)),
        "loop_start_action": min(PROTECTED_ACTIONS + 1, len(actions)),
        "seed_source": str(SEED_RPL),
        "generation": 0,
        "agent_index": 0,
    }
    save_json(SEED_JSON, agent)
    save_json(CHAMPION_JSON, agent)
    return agent

def export_lua(agent):
    lines = [
        "-- Auto-generated by evolution_loop_walk_gru_live_v6.py",
        "TORIBASHAI_AGENT = {}",
        f'TORIBASHAI_AGENT.name = "{agent.get("name", "walk_gru_live_v6")}"',
        f'TORIBASHAI_AGENT.generation = {int(agent.get("generation", 0))}',
        f'TORIBASHAI_AGENT.agent_index = {int(agent.get("agent_index", 0))}',
        f'TORIBASHAI_AGENT.frames_per_action = {int(agent.get("frames_per_action", FRAMES_PER_ACTION))}',
        f'TORIBASHAI_AGENT.max_frames = {int(agent.get("max_frames", MAX_FRAMES))}',
        f'TORIBASHAI_AGENT.protected_actions = {int(agent.get("protected_actions", PROTECTED_ACTIONS))}',
        f'TORIBASHAI_AGENT.loop_start_action = {int(agent.get("loop_start_action", PROTECTED_ACTIONS+1))}',
        "TORIBASHAI_AGENT.control_joints = {" + ", ".join(map(str, agent.get("control_joints", CONTROL_JOINTS))) + "}",
        "TORIBASHAI_AGENT.actions = {",
    ]
    for a in agent["actions"]:
        lines.append("    {" + ", ".join(str(int(v)) for v in a) + "},")
    lines += ["}", "WALK_GRU_AGENT = TORIBASHAI_AGENT", "return TORIBASHAI_AGENT"]
    AGENT_LUA.write_text("\n".join(lines) + "\n", encoding="utf-8")

def reset_toribash():
    try:
        subprocess.run(["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"], check=False)
        time.sleep(0.08)
        p = subprocess.Popen(["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE)
        p.communicate(RESET_COMMAND.encode("utf-8"))
        subprocess.run(["xdotool", "key", "t"], check=False)
        time.sleep(0.06)
        subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
        subprocess.run(["xdotool", "key", "BackSpace"], check=False)
        subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
        subprocess.run(["xdotool", "key", "Return"], check=False)
        # kick physics quickly after reset/load
        time.sleep(0.20)
        subprocess.run(["xdotool", "key", "space"], check=False)
    except Exception as e:
        print("reset error:", e)

def wait_result(timeout=70):
    start = time.time()
    while time.time()-start < timeout:
        if RESULT_PATH.exists():
            try:
                data = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return data
            except Exception:
                pass
        time.sleep(0.2)
    return {"score": -999999, "reason": "timeout", "frames": 0}

def mutate(agent):
    child = copy.deepcopy(agent)
    muts = 0
    protected = int(child.get("protected_actions", PROTECTED_ACTIONS))
    for ai, a in enumerate(child["actions"]):
        # protect true JSON launch/prefix
        if ai < protected:
            continue
        rate = LOOP_MUT_RATE if ai >= protected else BASE_MUT_RATE
        for j in range(len(a)):
            if random.random() < rate:
                cur = int(a[j])
                if random.random() < NO_CHANGE_BIAS:
                    new = cur
                else:
                    choices = [v for v in JOINT_VALUES if v != cur]
                    new = random.choice(choices)
                if new != cur:
                    a[j] = new
                    muts += 1
    child["mutations"] = muts
    return child

def evaluate(agent, gen, idx):
    agent = copy.deepcopy(agent)
    agent["generation"] = gen
    agent["agent_index"] = idx
    agent["name"] = f"walk_gru_live_v6_gen_{gen:05d}_agent_{idx:03d}"
    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_lua(agent)
    RESULT_PATH.unlink(missing_ok=True)
    print(f"GEN {gen} AGENT {idx} muts={agent.get('mutations',0)}")
    reset_toribash()
    result = wait_result()
    score = float(result.get("score", -999999))
    save_json(POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json", result)
    print("score", score, result)
    return score, result, path

def setup():
    POP_DIR.mkdir(parents=True, exist_ok=True); BEST_DIR.mkdir(parents=True, exist_ok=True)
    if not PROJECT_LUA.exists():
        raise FileNotFoundError(f"Missing Lua in scripts: {PROJECT_LUA}")
    shutil.copy2(PROJECT_LUA, STEAM_LUA)
    agent = ensure_seed()
    export_lua(agent)
    print("Lua copied:", STEAM_LUA)
    print("Seed actions:", len(agent["actions"]))
    print("Agent exported:", AGENT_LUA)
    print("Load in Toribash: ls toribash_walk_gru_live_v6.lua")

def one_gen():
    setup()
    champion = load_json(CHAMPION_JSON) if CHAMPION_JSON.exists() else ensure_seed()
    best_score = -999999; best_path = None; best_result = None
    for i in range(POP_SIZE):
        cand = copy.deepcopy(champion) if i == 0 else mutate(champion)
        if i == 0: cand["mutations"] = 0; cand["elite_copy"] = True
        score, result, path = evaluate(cand, 0, i)
        if score > best_score:
            best_score, best_path, best_result = score, path, result
    print("BEST", best_score, best_path, best_result)
    if best_path:
        shutil.copy2(best_path, CHAMPION_JSON)
        save_json(BEST_DIR / f"champion_score_{best_score:.2f}.json", load_json(best_path))

def run():
    setup()
    champion_score = -999999
    champion = load_json(CHAMPION_JSON)
    for gen in range(GENERATIONS):
        best_score = -999999; best_path = None; best_result = None
        for i in range(POP_SIZE):
            cand = copy.deepcopy(champion) if i == 0 else mutate(champion)
            if i == 0: cand["mutations"] = 0; cand["elite_copy"] = True
            score, result, path = evaluate(cand, gen, i)
            if score > best_score:
                best_score, best_path, best_result = score, path, result
        if best_score > champion_score and best_path:
            champion_score = best_score
            champion = load_json(best_path)
            shutil.copy2(best_path, CHAMPION_JSON)
            save_json(BEST_DIR / f"champion_gen_{gen:05d}_score_{best_score:.2f}.json", champion)
            print("NEW CHAMPION", champion_score)
        else:
            print("No improvement", best_score, "champ", champion_score)

def main():
    import sys
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    if cmd == "setup": setup()
    elif cmd == "one-gen": one_gen()
    elif cmd == "run": run()
    else:
        print("Usage: setup | one-gen | run")

if __name__ == "__main__":
    main()
