#!/usr/bin/env python3
"""
generate_xioi_master_final_v6_1_exact_actions.py

V6.1 fixes V6:
- reads ALL joint/value pairs from each JOINT line, not only the first pair
- uses promoted champion xioi_master_final_v5_champion.rpl
- writes a native Lua table, no JSON parser
"""
from __future__ import annotations

import re
import shutil
from collections import defaultdict
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"
GEN_DIR = ROOT / "generated_replays"
STEAM_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

CANDIDATES = [
    GEN_DIR / "xioi_master_final_v5_champion.rpl",
    GEN_DIR / "xioi_master_final_v5_loop_10.rpl",
    Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/replay/xioi_master_final_v5_champion.rpl",
]

OUT_PROJECT = GEN_DIR / "xioi_master_final_v6_1_exact_actions.lua"
OUT_STEAM = STEAM_SCRIPT_DIR / "xioi_master_final_v6_1_exact_actions.lua"

FRAME_RE = re.compile(r"^FRAME\s+(-?\d+)\s*;")
JOINT_RE = re.compile(r"^JOINT\s+0\s*;\s*(.*)$")


def find_champion() -> Path:
    for p in CANDIDATES:
        if p.exists():
            return p
    hits = sorted(GEN_DIR.glob("xioi_master_final_v5*.rpl")) + sorted(GEN_DIR.glob("*v30*23*mut*.rpl"))
    if hits:
        return hits[0]
    raise FileNotFoundError("Champion introuvable: attendu generated_replays/xioi_master_final_v5_champion.rpl")


def parse_actions(path: Path) -> dict[int, list[tuple[int, int]]]:
    current_frame: int | None = None
    actions: dict[int, list[tuple[int, int]]] = defaultdict(list)

    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        m = FRAME_RE.match(line)
        if m:
            current_frame = int(m.group(1))
            continue

        m = JOINT_RE.match(line)
        if m and current_frame is not None:
            nums = [int(x) for x in re.findall(r"-?\d+", m.group(1))]
            # Format Toribash: JOINT 0; joint value joint value ...
            for i in range(0, len(nums) - 1, 2):
                j, v = nums[i], nums[i + 1]
                if 0 <= j <= 19 and 0 <= v <= 4:
                    actions[current_frame].append((j, v))

    clean: dict[int, list[tuple[int, int]]] = {}
    for fr, pairs in actions.items():
        # dernier état du même joint gagne
        d: dict[int, int] = {}
        for j, v in pairs:
            d[j] = v
        if d:
            clean[fr] = sorted(d.items())

    if not clean:
        raise RuntimeError(f"Aucune action JOINT trouvée dans {path}")
    return dict(sorted(clean.items()))


def write_lua(actions: dict[int, list[tuple[int, int]]], source: Path) -> None:
    frames = sorted(actions)
    total_pairs = sum(len(pairs) for pairs in actions.values())
    lines: list[str] = []
    lines.append("-- Auto-generated by generate_xioi_master_final_v6_1_exact_actions.py")
    lines.append(f"-- source: {source}")
    lines.append("XIOI_MASTER_FINAL_V6_1 = {")
    lines.append('  name = "xioi_master_final_v6_1_exact",')
    lines.append(f"  source = {source.name!r},")
    lines.append(f"  action_count = {len(frames)},")
    lines.append(f"  pair_count = {total_pairs},")
    lines.append(f"  max_frame = {max(frames)},")
    lines.append("  actions = {")
    for fr in frames:
        pair_text = ", ".join("{%d,%d}" % (j, v) for j, v in actions[fr])
        lines.append(f"    [{fr}] = {{ {pair_text} }},")
    lines.append("  }")
    lines.append("}")
    lines.append("return XIOI_MASTER_FINAL_V6_1")

    OUT_PROJECT.parent.mkdir(parents=True, exist_ok=True)
    OUT_PROJECT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    STEAM_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(OUT_PROJECT, OUT_STEAM)


def main() -> None:
    src = find_champion()
    actions = parse_actions(src)
    write_lua(actions, src)
    print("Champion:", src)
    print("Action frames:", len(actions))
    print("Total pairs:", sum(len(p) for p in actions.values()))
    print("Frame range:", min(actions), "->", max(actions))
    print("Project actions:", OUT_PROJECT)
    print("Steam actions:", OUT_STEAM)


if __name__ == "__main__":
    main()
