#!/usr/bin/env python3
"""
generate_xioi_live_actions_v26.py

Génère des actions pour le runner live V26.
Modes:
  - sampled: rejoue le vrai Xioi-only dataset, pour valider la mécanique
  - gru: utilise le GRU Xioi-only, mais avec diversité temporelle depuis les seeds dataset

Sorties:
  generated_replays/xioi_v26_live_actions.json
  Steam data/script/xioi_v26_live_actions_table.lua
"""
from __future__ import annotations

import json
import random
import shutil
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

ROOT = Path.home() / "Documents" / "ToribashAI"
DATASET_PATH = ROOT / "datasets" / "ml" / "xioi_only_v26_sequences.jsonl"
MODEL_PATH = ROOT / "models" / "xioi_gru_v26.pt"
OUT_JSON = ROOT / "generated_replays" / "xioi_v26_live_actions.json"
TORIBASH_SCRIPT_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
OUT_LUA_TABLE = TORIBASH_SCRIPT_DIR / "xioi_v26_live_actions_table.lua"

MODE = "sampled"  # sampled est plus utile en premier test; passe à "gru" après validation.
GENERATED_STEPS = 220
TURNFRAMES = 5
SEED = 2601
HIDDEN = 128
NUM_LAYERS = 1

random.seed(SEED)
torch.manual_seed(SEED)


class XioiGRU(nn.Module):
    def __init__(self, state_dim: int):
        super().__init__()
        self.gru = nn.GRU(state_dim, HIDDEN, num_layers=NUM_LAYERS, batch_first=True)
        self.head = nn.Sequential(nn.LayerNorm(HIDDEN), nn.Linear(HIDDEN, 20 * 5))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out, _ = self.gru(x)
        z = out[:, -1, :]
        return self.head(z).view(-1, 20, 5)


def load_rows() -> list[dict[str, Any]]:
    rows = []
    with DATASET_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        raise RuntimeError("Dataset vide")
    return rows


def action_to_pairs(action: list[int], max_pairs: int = 12) -> list[list[int]]:
    pairs = []
    for j, v in enumerate(action):
        v = int(v)
        if v != 0:
            pairs.append([int(j), v])
    return pairs[:max_pairs]


def sampled_actions(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    # Rejoue l'ordre temporel du dataset Xioi, puis boucle si nécessaire.
    ordered = sorted(rows, key=lambda r: int(r.get("target_frame", 0)))
    actions = []
    for step in range(GENERATED_STEPS):
        r = ordered[step % len(ordered)]
        pairs = action_to_pairs(r["action"], max_pairs=14)
        actions.append({
            "frame": step * TURNFRAMES,
            "pairs": pairs,
            "source_frame": r.get("target_frame"),
            "mode": "sampled",
        })
    return actions


def gru_actions(rows: list[dict[str, Any]], device: torch.device) -> list[dict[str, Any]]:
    ckpt = torch.load(MODEL_PATH, map_location=device)
    state_dim = int(ckpt.get("state_dim", len(rows[0]["state_seq"][0])))
    model = XioiGRU(state_dim).to(device)
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    # Important: on ne garde pas le même seed tout du long. On fait une trajectoire guidée par les vrais états Xioi
    # pour éviter le collapse pose fixe observé en V24.
    ordered = sorted(rows, key=lambda r: int(r.get("target_frame", 0)))
    actions = []
    for step in range(GENERATED_STEPS):
        seed_row = ordered[step % len(ordered)]
        x = torch.tensor([seed_row["state_seq"]], dtype=torch.float32, device=device)
        with torch.no_grad():
            logits = model(x)[0]
            # légère exploration déterministe: argmax, mais on force au moins les non-zéros vrais si collapse total
            pred = logits.argmax(dim=-1).detach().cpu().tolist()
        pairs = action_to_pairs(pred, max_pairs=14)
        if len(pairs) < 2:
            pairs = action_to_pairs(seed_row["action"], max_pairs=14)
        actions.append({
            "frame": step * TURNFRAMES,
            "pairs": pairs,
            "source_frame": seed_row.get("target_frame"),
            "mode": "gru_guided",
        })
    return actions


def write_lua_table(actions: list[dict[str, Any]]) -> None:
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("-- Auto-generated by generate_xioi_live_actions_v26.py")
    lines.append("XIOI_V26_ACTIONS = {")
    for a in actions:
        frame = int(a["frame"])
        parts = []
        for j, v in a.get("pairs", []):
            parts.append("{" + str(int(j)) + "," + str(int(v)) + "}")
        lines.append(f"  [{frame}] = {{ {', '.join(parts)} }},")
    lines.append("}")
    lines.append(f"XIOI_V26_ACTION_COUNT = {len(actions)}")
    lines.append(f"XIOI_V26_TURNFRAMES = {TURNFRAMES}")
    OUT_LUA_TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = load_rows()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Device:", device)
    print("Rows:", len(rows))
    print("Mode:", MODE)

    if MODE == "gru":
        actions = gru_actions(rows, device)
    else:
        actions = sampled_actions(rows)

    data = {
        "version": 26,
        "name": "xioi_v26_live_actions",
        "mode": MODE,
        "turnframes": TURNFRAMES,
        "generated_steps": GENERATED_STEPS,
        "actions": actions,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(data, indent=2), encoding="utf-8")
    write_lua_table(actions)

    print("Saved JSON:", OUT_JSON)
    print("Saved Lua table:", OUT_LUA_TABLE)
    print("First actions:", actions[:5])


if __name__ == "__main__":
    main()
