#!/usr/bin/env python3
"""
generate_xioi_teacher_forced_actions_v27.py

Étape 3 / V27:
  Génération teacher-forced / guidée par les vrais états Xioi.

Pourquoi:
  La génération ouverte collapse facilement en pose fixe.
  Ici, chaque prédiction reçoit une vraie fenêtre d'états Xioi, donc on teste si le GRU sait
  imiter localement la boucle sans dériver.

Sorties:
  generated_replays/xioi_teacher_forced_v27_actions.json
  data/script/xioi_v27_live_actions_table.lua
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

ROOT = Path.home() / "Documents" / "ToribashAI"
DATASET_PATH = ROOT / "datasets" / "ml" / "xioi_only_v26_sequences.jsonl"
MODEL_PATH = ROOT / "models" / "xioi_gru_overfit_v27.pt"
FALLBACK_MODEL = ROOT / "models" / "xioi_gru_v26.pt"
OUT_JSON = ROOT / "generated_replays" / "xioi_teacher_forced_v27_actions.json"
TORIBASH_SCRIPT_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
OUT_LUA_TABLE = TORIBASH_SCRIPT_DIR / "xioi_v27_live_actions_table.lua"

GENERATED_STEPS = 260
TURNFRAMES = 5
ACTION_DIM = 20
CLASSES = 5


class FlexibleXioiGRU(nn.Module):
    def __init__(self, state_dim: int, hidden: int, num_layers: int, overfit_head: bool):
        super().__init__()
        self.gru = nn.GRU(state_dim, hidden, num_layers=num_layers, batch_first=True, dropout=0.0)
        if overfit_head:
            self.head = nn.Sequential(nn.LayerNorm(hidden), nn.Linear(hidden, hidden), nn.GELU(), nn.Linear(hidden, ACTION_DIM * CLASSES))
        else:
            self.head = nn.Sequential(nn.LayerNorm(hidden), nn.Linear(hidden, ACTION_DIM * CLASSES))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out, _ = self.gru(x)
        z = out[:, -1, :]
        return self.head(z).view(-1, ACTION_DIM, CLASSES)


def load_rows() -> list[dict[str, Any]]:
    rows = []
    with DATASET_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        raise RuntimeError("Dataset vide")
    return sorted(rows, key=lambda r: int(r.get("target_frame", 0)))


def load_model(device: torch.device):
    path = MODEL_PATH if MODEL_PATH.exists() else FALLBACK_MODEL
    ckpt = torch.load(path, map_location=device)
    state_dim = int(ckpt.get("state_dim"))
    hidden = int(ckpt.get("hidden", 128))
    num_layers = int(ckpt.get("num_layers", 1))
    # Le modèle V27 overfit a une couche Linear hidden->hidden en plus.
    keys = ckpt["model_state"].keys()
    overfit_head = any(k.startswith("head.3") for k in keys)
    model = FlexibleXioiGRU(state_dim, hidden, num_layers, overfit_head).to(device)
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    print("Model:", path)
    print("Architecture: hidden", hidden, "layers", num_layers, "overfit_head", overfit_head)
    return model, path


def action_to_pairs(action: list[int], max_pairs: int = 14) -> list[list[int]]:
    pairs = []
    for j, v in enumerate(action):
        v = int(v)
        if v != 0:
            pairs.append([j, v])
    return pairs[:max_pairs]


def write_lua_table(actions: list[dict[str, Any]]) -> None:
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Auto-generated by generate_xioi_teacher_forced_actions_v27.py",
        "XIOI_V27_ACTIONS = {",
    ]
    for a in actions:
        pairs = ", ".join("{" + str(int(j)) + "," + str(int(v)) + "}" for j, v in a.get("pairs", []))
        lines.append(f"  [{int(a['frame'])}] = {{ {pairs} }},")
    lines.extend([
        "}",
        f"XIOI_V27_ACTION_COUNT = {len(actions)}",
        f"XIOI_V27_TURNFRAMES = {TURNFRAMES}",
    ])
    OUT_LUA_TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = load_rows()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model, model_path = load_model(device)
    print("Rows:", len(rows), "Device:", device)

    actions = []
    for step in range(GENERATED_STEPS):
        r = rows[step % len(rows)]
        x = torch.tensor([r["state_seq"]], dtype=torch.float32, device=device)
        with torch.no_grad():
            pred = model(x)[0].argmax(dim=-1).detach().cpu().tolist()
        pairs = action_to_pairs(pred)
        # Safety: si le modèle prédit trop peu, on garde le vrai label correspondant pour ne pas tester du vide.
        if len(pairs) < 2:
            pairs = action_to_pairs(r["action"])
        actions.append({
            "frame": step * TURNFRAMES,
            "pairs": pairs,
            "source_frame": r.get("target_frame"),
            "mode": "teacher_forced_gru_v27",
        })

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps({
        "version": 27,
        "mode": "teacher_forced",
        "model": str(model_path),
        "turnframes": TURNFRAMES,
        "actions": actions,
    }, indent=2), encoding="utf-8")
    write_lua_table(actions)

    print("Saved JSON:", OUT_JSON)
    print("Saved Lua table:", OUT_LUA_TABLE)
    print("First actions:", actions[:5])


if __name__ == "__main__":
    main()
