#!/usr/bin/env python3
"""
generate_xioi_champion_exact_actions_v31_1.py

V31.1 = champion exact runner.

Lit le replay champion xioi_v30_23_mut.rpl, extrait uniquement les JOINT,
et écrit une table Lua native pour éviter les bugs de parsing JSON côté Toribash.

Sorties:
  generated_replays/xioi_champion_exact_actions_v31_1.lua
  data/script/xioi_champion_exact_actions_v31_1.lua
"""

from __future__ import annotations

import re
import shutil
from collections import defaultdict
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"
GEN_DIR = ROOT / "generated_replays"

STEAM_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

# Champion promu / sélectionné.
CANDIDATES = [
    GEN_DIR / "xioi_v30_champion.rpl",
    GEN_DIR / "xioi_v30_23_mut.rpl",
    Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/replay/xioi_v30_23_mut.rpl",
]

OUT_PROJECT = GEN_DIR / "xioi_champion_exact_actions_v31_1.lua"
OUT_STEAM = STEAM_SCRIPT_DIR / "xioi_champion_exact_actions_v31_1.lua"

FRAME_RE = re.compile(r"^FRAME\s+(-?\d+)\s*;")
JOINT_RE = re.compile(r"^JOINT\s+0\s*;\s*(.*)$")


def find_champion() -> Path:
    for p in CANDIDATES:
        if p.exists():
            return p
    hits = sorted(GEN_DIR.glob("*v30*23*mut*.rpl")) + sorted(GEN_DIR.glob("*champion*.rpl"))
    if hits:
        return hits[0]
    raise FileNotFoundError("Impossible de trouver le champion V30/V31. Attendu: xioi_v30_23_mut.rpl ou xioi_v30_champion.rpl")


def parse_rpl_actions(path: Path) -> dict[int, list[tuple[int, int]]]:
    current_frame: int | None = None
    actions: dict[int, list[tuple[int, int]]] = defaultdict(list)

    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        m = FRAME_RE.match(line)
        if m:
            current_frame = int(m.group(1))
            continue

        m = JOINT_RE.match(line)
        if m and current_frame is not None:
            nums = [int(x) for x in re.findall(r"-?\d+", m.group(1))]
            # Format attendu: JOINT 0; joint value joint value...
            for i in range(0, len(nums) - 1, 2):
                j, v = nums[i], nums[i + 1]
                if 0 <= j <= 19 and 0 <= v <= 4:
                    actions[current_frame].append((j, v))

    # Déduplique par joint dans chaque frame, le dernier gagne.
    cleaned: dict[int, list[tuple[int, int]]] = {}
    for fr, pairs in actions.items():
        d = {}
        for j, v in pairs:
            d[j] = v
        cleaned[fr] = sorted(d.items())
    return cleaned


def write_lua_table(actions: dict[int, list[tuple[int, int]]], source: Path) -> None:
    frames = sorted(actions)
    lines: list[str] = []
    lines.append("-- Auto-generated by generate_xioi_champion_exact_actions_v31_1.py")
    lines.append(f"-- source: {source}")
    lines.append("XIOI_CHAMPION_EXACT_V31_1 = {")
    lines.append('  name = "xioi_champion_exact_v31_1",')
    lines.append(f"  source = {source.name!r},")
    lines.append(f"  action_count = {len(frames)},")
    lines.append("  actions = {")
    for fr in frames:
        pairs = actions[fr]
        pair_text = ", ".join("{%d,%d}" % (j, v) for j, v in pairs)
        lines.append(f"    [{fr}] = {{ {pair_text} }},")
    lines.append("  }")
    lines.append("}")
    lines.append("return XIOI_CHAMPION_EXACT_V31_1")

    OUT_PROJECT.parent.mkdir(parents=True, exist_ok=True)
    OUT_PROJECT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    STEAM_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(OUT_PROJECT, OUT_STEAM)


def main() -> None:
    source = find_champion()
    actions = parse_rpl_actions(source)
    if not actions:
        raise RuntimeError(f"Aucune action JOINT trouvée dans {source}")

    write_lua_table(actions, source)

    total_pairs = sum(len(p) for p in actions.values())
    print("Champion:", source)
    print("Frames actions:", len(actions))
    print("Total pairs:", total_pairs)
    print("First frames:", sorted(actions)[:10])
    print("Project Lua:", OUT_PROJECT)
    print("Steam Lua:", OUT_STEAM)


if __name__ == "__main__":
    main()
