#!/usr/bin/env python3
"""
generate_xioi_master_final_v6_exact_actions.py

V6 exact runner source exporter.
Reads the promoted champion replay:
  generated_replays/xioi_master_final_v5_champion.rpl
and exports a Lua table containing exact JOINT commands by frame.

No GRU, no mutation, no pilot. Goal: make live Lua reproduce the champion
as faithfully as possible.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"
SRC = ROOT / "generated_replays" / "xioi_master_final_v5_champion.rpl"
OUT_DIR = ROOT / "generated_replays"
OUT_LUA = OUT_DIR / "xioi_master_final_v6_exact_actions.lua"

STEAM_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)
STEAM_OUT_LUA = STEAM_SCRIPT_DIR / "xioi_master_final_v6_exact_actions.lua"

FRAME_RE = re.compile(r"^FRAME\s+(-?\d+)\s*;")
JOINT_RE = re.compile(r"^JOINT\s+0\s*;\s*(\d+)\s+(\d+)")


def parse_replay(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"Champion replay not found: {path}")

    actions: dict[int, list[tuple[int, int]]] = {}
    current_frame: int | None = None

    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        m = FRAME_RE.match(line)
        if m:
            current_frame = int(m.group(1))
            actions.setdefault(current_frame, [])
            continue
        m = JOINT_RE.match(line)
        if m and current_frame is not None:
            j = int(m.group(1))
            v = int(m.group(2))
            if 0 <= j <= 19 and 1 <= v <= 4:
                actions.setdefault(current_frame, []).append((j, v))

    # remove empty frames but keep order
    clean = {f: pairs for f, pairs in sorted(actions.items()) if pairs}
    if not clean:
        raise RuntimeError("No JOINT actions found in champion replay")
    return clean


def write_lua_table(actions: dict[int, list[tuple[int, int]]], out: Path):
    max_frame = max(actions)
    total_pairs = sum(len(p) for p in actions.values())
    lines = []
    lines.append("-- Auto-generated by generate_xioi_master_final_v6_exact_actions.py")
    lines.append("-- Exact JOINT table from xioi_master_final_v5_champion.rpl")
    lines.append("XIOI_MASTER_FINAL_V6_ACTIONS = {")
    for frame, pairs in sorted(actions.items()):
        parts = ", ".join("{%d,%d}" % (j, v) for j, v in pairs)
        lines.append(f"  [{frame}] = {{ {parts} }},")
    lines.append("}")
    lines.append(f"XIOI_MASTER_FINAL_V6_MAX_FRAME = {max_frame}")
    lines.append(f"XIOI_MASTER_FINAL_V6_ACTION_COUNT = {len(actions)}")
    lines.append(f"XIOI_MASTER_FINAL_V6_PAIR_COUNT = {total_pairs}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    actions = parse_replay(SRC)
    write_lua_table(actions, OUT_LUA)
    STEAM_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(OUT_LUA, STEAM_OUT_LUA)
    print("Source:", SRC)
    print("Actions:", len(actions))
    print("Pairs:", sum(len(p) for p in actions.values()))
    print("Max frame:", max(actions))
    print("Project Lua table:", OUT_LUA)
    print("Steam Lua table:", STEAM_OUT_LUA)


if __name__ == "__main__":
    main()
