#!/usr/bin/env python3
"""
generate_xioi_champion_live_actions_v31.py

Génère une table Lua d'actions depuis le champion V30/V31.
Modes:
  sampled: rejoue les vraies actions du champion dataset.
  gru_teacher: prédictions GRU teacher-forced sur les états du dataset.

Par défaut, on mixe sampled + gru_teacher pour éviter le collapse.
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

ROOT = Path.home() / "Documents" / "ToribashAI"
DATASET_PATH = ROOT / "datasets" / "ml" / "xioi_champion_v31_sequences.jsonl"
MODEL_PATH = ROOT / "models" / "xioi_champion_gru_v31.pt"
OUT_JSON = ROOT / "generated_replays" / "xioi_champion_v31_live_actions.json"
TORIBASH_SCRIPT_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
OUT_LUA_TABLE = TORIBASH_SCRIPT_DIR / "xioi_champion_v31_live_actions_table.lua"

GENERATED_STEPS = 320
TURNFRAMES = 5
ACTION_DIM = 20
CLASSES = 5
MODE = "hybrid"  # sampled | gru_teacher | hybrid
MAX_PAIRS = 16


class FlexibleChampionGRU(nn.Module):
    def __init__(self, state_dim: int, hidden: int, num_layers: int):
        super().__init__()
        self.gru = nn.GRU(state_dim, hidden, num_layers=num_layers, batch_first=True, dropout=0.0)
        self.head = nn.Sequential(
            nn.LayerNorm(hidden), nn.Linear(hidden, hidden), nn.GELU(), nn.Linear(hidden, ACTION_DIM * CLASSES)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out, _ = self.gru(x)
        z = out[:, -1]
        return self.head(z).view(-1, ACTION_DIM, CLASSES)


def load_rows() -> list[dict[str, Any]]:
    rows = []
    with DATASET_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        raise RuntimeError("Dataset vide")
    return sorted(rows, key=lambda r: int(r.get("target_frame", 0)))


def load_model(device: torch.device):
    if not MODEL_PATH.exists():
        print("Model absent, mode sampled only:", MODEL_PATH)
        return None
    ckpt = torch.load(MODEL_PATH, map_location=device)
    model = FlexibleChampionGRU(int(ckpt["state_dim"]), int(ckpt.get("hidden", 224)), int(ckpt.get("num_layers", 2))).to(device)
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    print("Model:", MODEL_PATH)
    print("Metrics:", ckpt.get("metrics"))
    return model


def action_to_pairs(action: list[int]) -> list[list[int]]:
    pairs = []
    for j, v in enumerate(action):
        v = int(v)
        if v != 0:
            pairs.append([j, v])
    return pairs[:MAX_PAIRS]


def write_lua_table(actions: list[dict[str, Any]]) -> None:
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Auto-generated by generate_xioi_champion_live_actions_v31.py",
        "XIOI_V31_ACTIONS = {",
    ]
    for a in actions:
        pairs = ", ".join("{" + str(int(j)) + "," + str(int(v)) + "}" for j, v in a.get("pairs", []))
        lines.append(f"  [{int(a['frame'])}] = {{ {pairs} }},")
    lines.extend([
        "}",
        f"XIOI_V31_ACTION_COUNT = {len(actions)}",
        f"XIOI_V31_TURNFRAMES = {TURNFRAMES}",
    ])
    OUT_LUA_TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = load_rows()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = load_model(device)
    print("Rows:", len(rows), "Device:", device, "Mode:", MODE)

    actions = []
    counter = Counter()
    for step in range(GENERATED_STEPS):
        r = rows[step % len(rows)]
        sampled_pairs = action_to_pairs(r["action"])
        pred_pairs = []
        if model is not None:
            x = torch.tensor([r["state_seq"]], dtype=torch.float32, device=device)
            with torch.no_grad():
                pred = model(x)[0].argmax(dim=-1).detach().cpu().tolist()
            pred_pairs = action_to_pairs(pred)

        if MODE == "sampled" or model is None:
            pairs = sampled_pairs
            mode = "sampled"
        elif MODE == "gru_teacher":
            pairs = pred_pairs if pred_pairs else sampled_pairs
            mode = "gru_teacher"
        else:
            # Hybrid: 2 frames sampled, 1 frame GRU teacher, pour exploiter le modèle sans perdre la chorégraphie.
            if step % 3 == 2 and len(pred_pairs) >= 2:
                pairs = pred_pairs
                mode = "gru_teacher"
            else:
                pairs = sampled_pairs
                mode = "sampled"

        for j, v in pairs:
            counter[(j, v)] += 1
        actions.append({
            "frame": step * TURNFRAMES,
            "pairs": pairs,
            "source_frame": r.get("target_frame"),
            "mode": mode,
        })

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps({
        "version": 31,
        "mode": MODE,
        "turnframes": TURNFRAMES,
        "dataset": str(DATASET_PATH),
        "model": str(MODEL_PATH) if MODEL_PATH.exists() else None,
        "actions": actions,
        "top_pairs": [([j, v], c) for (j, v), c in counter.most_common(30)],
    }, indent=2), encoding="utf-8")
    write_lua_table(actions)
    print("Saved JSON:", OUT_JSON)
    print("Saved Lua table:", OUT_LUA_TABLE)
    print("Actions:", len(actions))
    print("First:", actions[:5])
    print("Top pairs:", [([j, v], c) for (j, v), c in counter.most_common(12)])


if __name__ == "__main__":
    main()
