-- toribash_walk_gru_live_runner_v1.lua
-- ToribashAI walk_gru_live_v1
-- Live runner: reads a Lua-table agent generated by Python, applies joints, auto-starts, scores, overlays gen/agent/pop.

local VERSION = "walk_gru_live_v1"
local HOOK = "toribashai_walk_gru_live_v1"
local AGENT_FILE = "toribash_walk_gru_live_agent_v1.lua"
local RESULT_FILE = "toribash_walk_gru_live_result_v1.json"
local META_FILE = "toribash_walk_gru_live_meta_v1.txt"

local agent = nil
local actions = {}
local next_action_idx = 1
local applied_count = 0
local ok_count = 0
local fail_count = 0
local started = false
local auto_ticks = 0
local wrote = false
local last_frame = 0
local frames_alive = 0
local start_y = nil
local last_y = nil
local best_y = nil
local min_body_z = 999999
local fall_frame = nil
local last_action_text = "none"

local meta_gen = "?"
local meta_agent = "?"
local meta_pop = "?"
local meta_score = "?"

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local s = f:read("*all")
    f:close()
    return s
end

local function write_file(path, txt)
    local f = io.open(path, "w")
    if not f then return false end
    f:write(txt)
    f:close()
    return true
end

local function json_escape(s)
    s = tostring(s or "")
    s = s:gsub('\\', '\\\\')
    s = s:gsub('"', '\\"')
    return s
end

local function load_meta()
    local s = read_file(META_FILE)
    if not s then return end
    meta_gen = s:match("gen=([^\n]+)") or meta_gen
    meta_agent = s:match("agent=([^\n]+)") or meta_agent
    meta_pop = s:match("population=([^\n]+)") or meta_pop
    meta_score = s:match("parent_score=([^\n]+)") or meta_score
end

local function load_agent()
    local ok, data = pcall(dofile, AGENT_FILE)
    if not ok or type(data) ~= "table" then
        agent = { name = "missing_or_bad_agent", gen = "?", agent_id = "?", population = "?", max_frame = 900, actions = {} }
        actions = {}
        return false
    end
    agent = data
    actions = data.actions or {}
    table.sort(actions, function(a, b) return tonumber(a.frame or 0) < tonumber(b.frame or 0) end)
    return true
end

local function get_frame_safe()
    if get_world_state then
        local ok, ws = pcall(get_world_state)
        if ok and type(ws) == "table" then
            if ws.match_frame then return tonumber(ws.match_frame) or 0 end
            if ws.frame then return tonumber(ws.frame) or 0 end
        end
    end
    if get_game_frame then
        local ok, fr = pcall(get_game_frame)
        if ok and fr then return tonumber(fr) or 0 end
    end
    if get_frame then
        local ok, fr = pcall(get_frame)
        if ok and fr then return tonumber(fr) or 0 end
    end
    return last_frame or 0
end

local function get_body_pos_best_effort(player, body)
    if get_body_info then
        local ok, info = pcall(get_body_info, player, body)
        if ok and type(info) == "table" then
            if info.pos and type(info.pos) == "table" then
                return tonumber(info.pos.x or info.pos[1]), tonumber(info.pos.y or info.pos[2]), tonumber(info.pos.z or info.pos[3])
            end
            if info.x and info.y and info.z then
                return tonumber(info.x), tonumber(info.y), tonumber(info.z)
            end
        end
    end
    if get_body_pos then
        local ok, x, y, z = pcall(get_body_pos, player, body)
        if ok and x and y and z then return tonumber(x), tonumber(y), tonumber(z) end
    end
    return nil, nil, nil
end

local function sample_body()
    -- Best effort: average chest/lumbar/abs/hips when available.
    local ids = {1, 2, 3, 13, 14}
    local sx, sy, sz, n = 0, 0, 0, 0
    for _, id in ipairs(ids) do
        local x, y, z = get_body_pos_best_effort(0, id)
        if x and y and z then
            sx = sx + x; sy = sy + y; sz = sz + z; n = n + 1
        end
    end
    if n > 0 then return sx / n, sy / n, sz / n end
    return nil, nil, nil
end

local function set_joint_best_effort(j, v)
    local ok = false
    if set_joint_state then
        ok = pcall(function() set_joint_state(0, j, v) end)
        if not ok then ok = pcall(function() set_joint_state(j, v) end) end
    end
    if not ok and set_joint then
        ok = pcall(function() set_joint(0, j, v) end)
        if not ok then ok = pcall(function() set_joint(j, v) end) end
    end
    if ok then ok_count = ok_count + 1 else fail_count = fail_count + 1 end
    return ok
end

local function apply_action(a)
    if not a or not a.pairs then return end
    local pairs = a.pairs
    last_action_text = "f" .. tostring(a.frame or "?") .. " pairs=" .. tostring(#pairs)
    for _, p in ipairs(pairs) do
        local j = tonumber(p[1])
        local v = tonumber(p[2])
        if j and v and v ~= 0 then set_joint_best_effort(j, v) end
    end
    applied_count = applied_count + 1
end

local function try_autostart()
    -- Aggressive but safe auto-space / auto-play at the beginning and after reset.
    if auto_ticks > 45 then return end
    auto_ticks = auto_ticks + 1
    if run_cmd then
        pcall(function() run_cmd(" ") end)
        pcall(function() run_cmd("space") end)
        pcall(function() run_cmd("play") end)
    end
    if run_frames then pcall(function() run_frames(1) end) end
    if step_game then pcall(function() step_game() end) end
    if play then pcall(function() play() end) end
end

local function compute_score(reason)
    local dist = 0
    if start_y and best_y then
        dist = math.abs(best_y - start_y)
    elseif start_y and last_y then
        dist = math.abs(last_y - start_y)
    end
    local max_frame = tonumber(agent and agent.max_frame or 900) or 900
    local alive_bonus = frames_alive * 0.7
    local dist_bonus = dist * 45.0
    local action_bonus = applied_count * 0.2
    local fall_penalty = fall_frame and 700 or 0
    local low_penalty = 0
    if min_body_z < 5.0 then low_penalty = (5.0 - min_body_z) * 90 end
    return dist_bonus + alive_bonus + action_bonus - fall_penalty - low_penalty, dist, max_frame
end

local function write_result(reason)
    if wrote then return end
    wrote = true
    local score, dist, max_frame = compute_score(reason or "done")
    local txt = string.format([[{
  "version": "%s",
  "gen": "%s",
  "agent": "%s",
  "population": "%s",
  "score": %.6f,
  "distance_y_body": %.6f,
  "frames_alive": %d,
  "last_frame": %d,
  "max_frame": %d,
  "applied_actions": %d,
  "ok_count": %d,
  "fail_count": %d,
  "fall_frame": %s,
  "min_body_z": %.6f,
  "reason": "%s"
}
]], VERSION, json_escape(meta_gen), json_escape(meta_agent), json_escape(meta_pop), score, dist, frames_alive, last_frame or 0, max_frame, applied_count, ok_count, fail_count, fall_frame and tostring(fall_frame) or "null", min_body_z, json_escape(reason or "done"))
    write_file(RESULT_FILE, txt)
end

local function reset_local_state()
    next_action_idx = 1
    applied_count = 0
    ok_count = 0
    fail_count = 0
    started = false
    auto_ticks = 0
    wrote = false
    last_frame = 0
    frames_alive = 0
    start_y = nil
    last_y = nil
    best_y = nil
    min_body_z = 999999
    fall_frame = nil
    last_action_text = "none"
    load_meta()
    load_agent()
end

local function on_new_game()
    reset_local_state()
end

local function on_enter_frame()
    if not agent then load_agent() end
    load_meta()
    local fr = get_frame_safe()
    last_frame = fr

    if not started then
        try_autostart()
        if fr > 0 then started = true end
    else
        -- Continue nudging the sim so user doesn't have to keep pressing space.
        if auto_ticks < 45 then try_autostart() end
    end

    while actions[next_action_idx] and tonumber(actions[next_action_idx].frame or 0) <= fr do
        apply_action(actions[next_action_idx])
        next_action_idx = next_action_idx + 1
    end

    local x, y, z = sample_body()
    if y then
        if not start_y then start_y = y end
        last_y = y
        if not best_y then best_y = y end
        if math.abs(y - start_y) > math.abs(best_y - start_y) then best_y = y end
    end
    if z and z < min_body_z then min_body_z = z end

    if started then frames_alive = frames_alive + 1 end

    if started and fr > 140 and z and z < 4.3 and not fall_frame then
        fall_frame = fr
        write_result("fall_low_body")
    end

    local max_frame = tonumber(agent and agent.max_frame or 900) or 900
    if fr >= max_frame then write_result("max_frames") end
end

local function draw_overlay()
    if set_color then set_color(1, 1, 1, 1) end
    if draw_text then
        draw_text("ToribashAI walk_gru_live_v1", 40, 55, 1)
        draw_text("gen=" .. tostring(meta_gen) .. " agent=" .. tostring(meta_agent) .. "/" .. tostring(meta_pop), 40, 80, 1)
        draw_text("frame=" .. tostring(last_frame) .. " applied=" .. tostring(applied_count) .. "/" .. tostring(#actions), 40, 105, 1)
        draw_text("ok=" .. tostring(ok_count) .. " fail=" .. tostring(fail_count) .. " auto=" .. tostring(auto_ticks), 40, 130, 1)
        draw_text("last=" .. tostring(last_action_text), 40, 155, 1)
        if start_y and last_y then draw_text(string.format("bodyY %.2f -> %.2f", start_y, last_y), 40, 180, 1) end
        draw_text("parent=" .. tostring(meta_score), 40, 205, 1)
    end
end

load_meta()
load_agent()

if add_hook then
    add_hook("new_game", HOOK .. "_new", on_new_game)
    add_hook("enter_frame", HOOK .. "_step", on_enter_frame)
    add_hook("draw2d", HOOK .. "_draw", draw_overlay)
end
