#!/usr/bin/env python3
"""
export_root_walk_agent_lua_v1.py

Exporte evolution/root_walk_champion_v1.json vers un fichier Lua directement lisible
par toribash_root_walk_runner_v1.lua.

Usage:
  cd ~/Documents/ToribashAI
  python3 scripts/export_root_walk_agent_lua_v1.py \
    --agent evolution/root_walk_champion_v1.json \
    --out ~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script/toribashai_root_walk_agent_v1.lua
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEFAULT_TORIBASH_SCRIPT_DIR = Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"


def lua_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def to_lua(value: Any, indent: int = 0) -> str:
    sp = " " * indent
    sp2 = " " * (indent + 2)

    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return lua_quote(value)
    if isinstance(value, list):
        if not value:
            return "{}"
        parts = ["{"]
        for item in value:
            parts.append(sp2 + to_lua(item, indent + 2) + ",")
        parts.append(sp + "}")
        return "\n".join(parts)
    if isinstance(value, dict):
        if not value:
            return "{}"
        parts = ["{"]
        for k, v in value.items():
            # Numeric string keys become [14] = ...
            if isinstance(k, str) and k.isdigit():
                key = f"[{int(k)}]"
            elif isinstance(k, int):
                key = f"[{k}]"
            elif isinstance(k, str) and k.replace("_", "").isalnum() and not k[0].isdigit():
                key = k
            else:
                key = "[" + lua_quote(str(k)) + "]"
            parts.append(sp2 + f"{key} = " + to_lua(v, indent + 2) + ",")
        parts.append(sp + "}")
        return "\n".join(parts)
    raise TypeError(f"Unsupported type: {type(value)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--agent", default="evolution/root_walk_champion_v1.json")
    ap.add_argument("--out", default=str(DEFAULT_TORIBASH_SCRIPT_DIR / "toribashai_root_walk_agent_v1.lua"))
    args = ap.parse_args()

    agent_path = Path(args.agent).expanduser()
    out_path = Path(args.out).expanduser()
    data = json.loads(agent_path.read_text(encoding="utf-8"))

    text = "-- Auto-generated by export_root_walk_agent_lua_v1.py\nreturn " + to_lua(data, 0) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
