#!/usr/bin/env python3

import json
import sys
from pathlib import Path

PROJECT = Path.home() / "Documents" / "ToribashAI"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"


def main():

    if len(sys.argv) > 1:
        agent_json = Path(sys.argv[1])
    else:
        agent_json = PROJECT / "evolution" / "agent_current.json"

    agent = json.loads(
        agent_json.read_text(encoding="utf-8")
    )

    actions = agent["actions"]

    lines = []
    lines.append("-- Auto-generated by export_agent_lua_v1.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append("TORIBASHAI_AGENT.actions = {")

    for turn in actions:
        values = ", ".join(str(int(v)) for v in turn)
        lines.append(f"    {{ {values} }},")

    lines.append("}")
    lines.append("")

    OUT_LUA.write_text(
        "\n".join(lines),
        encoding="utf-8"
    )

    print("Exported:", OUT_LUA)
    print("Source:", agent_json)
    print("Agent:", agent["name"])
    print("Turns:", len(actions))


if __name__ == "__main__":
    main()
