#!/usr/bin/env python3
import json
from pathlib import Path

import torch
import torch.nn as nn

ROOT = Path.home() / "Documents" / "ToribashAI"

MODEL_PATH = ROOT / "models/walk_fullbody_gru_v4_gold_mix.pt"
DATASET_PATH = ROOT / "datasets/ml/walk_v4_gold_mix.jsonl"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
OUT_JSON = ROOT / "evolution" / "walk_fullbody_agent_v4_gold_mix_current.json"

AGENT_NAME = "walk_fullbody_v4_gold_mix"

SEQ_LEN = 8
NUM_TURNS = 45

ACTION_DIM = 20
NUM_CLASSES = 5
HIDDEN_SIZE = 160
NUM_LAYERS = 1
DROPOUT = 0.20

CONTROL_JOINTS = [
    4, 5, 6, 7,
    14, 15, 16,
    17, 18, 19,
]


class WalkGRU(nn.Module):
    def __init__(self, state_dim):
        super().__init__()

        self.gru = nn.GRU(
            input_size=state_dim,
            hidden_size=HIDDEN_SIZE,
            num_layers=NUM_LAYERS,
            batch_first=True,
            dropout=0.0,
        )

        self.head = nn.Sequential(
            nn.LayerNorm(HIDDEN_SIZE),
            nn.Dropout(DROPOUT),
            nn.Linear(HIDDEN_SIZE, 256),
            nn.GELU(),
            nn.Dropout(DROPOUT),
            nn.Linear(256, ACTION_DIM * NUM_CLASSES),
        )

    def forward(self, x):
        out, _ = self.gru(x)
        last = out[:, -1, :]
        logits = self.head(last)
        return logits.view(-1, ACTION_DIM, NUM_CLASSES)


def extract_state_sequence(ex):
    for key in ["states", "state_seq", "sequence", "x"]:
        if key in ex and isinstance(ex[key], list):
            return ex[key]
    raise KeyError("Aucune séquence d'état trouvée.")


def load_best_examples():
    items = []

    with DATASET_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue

            ex = json.loads(line)
            q = float(ex.get("walk_quality_score", 0.0))
            states = extract_state_sequence(ex)

            if len(states) != SEQ_LEN:
                continue

            items.append((q, states, ex))

    if not items:
        raise RuntimeError("Aucun exemple utilisable trouvé.")

    items.sort(key=lambda x: x[0], reverse=True)
    return items[:NUM_TURNS]


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by generate_walk_fullbody_agent_v2_quality.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append("TORIBASHAI_AGENT.control_joints = { 4, 5, 6, 7, 14, 15, 16, 17, 18, 19 }")
    lines.append("TORIBASHAI_AGENT.actions = {")

    for turn in agent["actions"]:
        values = ", ".join(str(int(v)) for v in turn)
        lines.append(f"    {{ {values} }},")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    OUT_LUA.write_text("\n".join(lines), encoding="utf-8")


def main():
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)

    checkpoint = torch.load(MODEL_PATH, map_location="cpu")
    state_dim = int(checkpoint["state_dim"])

    model = WalkGRU(state_dim)
    model.load_state_dict(checkpoint["model_state"])
    model.eval()

    examples = load_best_examples()

    actions = []
    qualities = []

    with torch.no_grad():
        for q, states, ex in examples:
            x = torch.tensor([states], dtype=torch.float32)
            logits = model(x)
            full_action = logits.argmax(dim=-1)[0].tolist()

            toribash_action = []
            for j in CONTROL_JOINTS:
                v = int(full_action[j])
                if v <= 0:
                    v = 3
                elif v > 4:
                    v = 4
                toribash_action.append(v)

            actions.append(toribash_action)
            qualities.append(q)

    agent = {
        "name": AGENT_NAME,
        "source_model": str(MODEL_PATH),
        "source_dataset": str(DATASET_PATH),
        "control_joints": CONTROL_JOINTS,
        "actions": actions,
        "qualities": qualities,
    }

    OUT_JSON.write_text(json.dumps(agent, indent=2), encoding="utf-8")
    export_lua(agent)

    print("Agent exporté")
    print("Lua :", OUT_LUA)
    print("JSON:", OUT_JSON)
    print("Turns:", len(actions))
    print("Qualité moyenne source:", round(sum(qualities) / len(qualities), 4))
    print("Première action:", actions[0])


if __name__ == "__main__":
    main()
