#!/usr/bin/env python3
import json
from pathlib import Path

import torch
import torch.nn as nn

PROJECT = Path.home() / "Documents" / "ToribashAI"

MODEL_PATH = PROJECT / "models" / "walk_fullbody_gru_v1.pt"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

OUT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
OUT_JSON = PROJECT / "evolution" / "walk_fullbody_agent_current.json"

SEQ_LEN = 8
NUM_TURNS = 45

NUM_JOINTS = 10
NUM_CLASSES = 5
INPUT_DIM = NUM_JOINTS
HIDDEN_SIZE = 128
NUM_LAYERS = 1
DROPOUT = 0.20

CONTROL_JOINTS = [
    4, 5, 6, 7,
    14, 15, 16,
    17, 18, 19,
]


class WalkGRU(nn.Module):
    def __init__(self):
        super().__init__()

        self.gru = nn.GRU(
            input_size=INPUT_DIM,
            hidden_size=HIDDEN_SIZE,
            num_layers=NUM_LAYERS,
            batch_first=True,
            dropout=0.0,
        )

        self.head = nn.Sequential(
            nn.Linear(HIDDEN_SIZE, 128),
            nn.ReLU(),
            nn.Dropout(DROPOUT),
            nn.Linear(128, NUM_JOINTS * NUM_CLASSES),
        )

    def forward(self, x):
        out, _ = self.gru(x)
        last = out[:, -1, :]
        logits = self.head(last)
        return logits.view(-1, NUM_JOINTS, NUM_CLASSES)


def sample_from_logits(logits, temperature=0.85):
    probs = torch.softmax(logits / temperature, dim=-1)
    return torch.multinomial(probs, num_samples=1).squeeze(-1)


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by generate_walk_fullbody_agent_v1.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append("TORIBASHAI_AGENT.control_joints = { 4, 5, 6, 7, 14, 15, 16, 17, 18, 19 }")
    lines.append("TORIBASHAI_AGENT.actions = {")

    for turn in agent["actions"]:
        values = ", ".join(str(int(v)) for v in turn)
        lines.append(f"    {{ {values} }},")

    lines.append("}")
    lines.append("")

    OUT_LUA.write_text("\n".join(lines), encoding="utf-8")


def main():
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    TORIBASH_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

    ckpt = torch.load(MODEL_PATH, map_location="cpu")

    model = WalkGRU()
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    torch.manual_seed(777)

    # Seed initial : posture neutre + bras légèrement actifs.
    current = [
        4, 4, 4, 4,  # bras
        3, 3, 3,     # jambe droite
        3, 3, 3,     # jambe gauche
    ]

    history = [current[:] for _ in range(SEQ_LEN)]
    actions = []

    for _ in range(NUM_TURNS):
        x = torch.tensor([history[-SEQ_LEN:]], dtype=torch.float32)

        with torch.no_grad():
            logits = model(x)[0]

        action = sample_from_logits(logits, temperature=0.90).tolist()

        actions.append(action)
        history.append(action)

    agent = {
        "version": 1,
        "name": "walk_fullbody_gru_v1_agent",
        "model": str(MODEL_PATH),
        "control_joints": CONTROL_JOINTS,
        "num_turns": NUM_TURNS,
        "actions": actions,
    }

    OUT_JSON.write_text(
        json.dumps(agent, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    export_lua(agent)

    print("Generated JSON:", OUT_JSON)
    print("Generated Lua:", OUT_LUA)
    print("Agent:", agent["name"])
    print("Turns:", len(actions))


if __name__ == "__main__":
    main()
