#!/usr/bin/env python3
import copy
import json
import random
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"

SEED_AGENT = ROOT / "evolution/upright_seed_v18.json"
CHAMPION_AGENT = ROOT / "evolution/upright_champion_v18.json"

PREVIOUS_CHAMPION = ROOT / "evolution/upright_champion_v17.json"
PREVIOUS_SEED = ROOT / "evolution/upright_seed_v17.json"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

AGENT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
RESULT_PATH = TORIBASH_SCRIPT_DIR / "toribashai_episode_result.json"

POP_DIR = ROOT / "evolution/population_upright_v18"
BEST_DIR = ROOT / "evolution/best_upright_v18"

POP_SIZE = 12
GENERATIONS = 999999

JOINT_VALUES = [0, 1, 2, 3, 4]

BASE_MUTATION_RATE = 0.035
EARLY_ACTIONS_PROTECTED = 4
EARLY_MUTATION_FACTOR = 0.30
NO_CHANGE_BIAS = 0.60
TARGET_ACTIONS = 25

RESET_COMMAND = "/lm ToribashAI/toribashai_goal_flat_v1.tbm"


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2), encoding="utf-8")


def adapt_agent_actions(agent):
    agent = copy.deepcopy(agent)
    actions = agent.get("actions", [])
    if not actions:
        return agent

    while len(actions) < TARGET_ACTIONS:
        actions.append(copy.deepcopy(actions[-1]))

    if len(actions) > TARGET_ACTIONS:
        actions = actions[:TARGET_ACTIONS]

    agent["actions"] = actions
    agent["target_actions"] = TARGET_ACTIONS
    agent["frames_per_action"] = 20
    agent["target_frames"] = 500
    return agent


def ensure_seed():
    if SEED_AGENT.exists():
        return

    if PREVIOUS_CHAMPION.exists():
        agent = adapt_agent_actions(load_json(PREVIOUS_CHAMPION))
        save_json(SEED_AGENT, agent)
        print("Seed V18 créée depuis champion V17:", PREVIOUS_CHAMPION)
        return

    if PREVIOUS_SEED.exists():
        agent = adapt_agent_actions(load_json(PREVIOUS_SEED))
        save_json(SEED_AGENT, agent)
        print("Seed V18 créée depuis seed V17:", PREVIOUS_SEED)
        return

    raise FileNotFoundError(f"Aucun champion/seed V17 trouvé pour créer {SEED_AGENT}")


def export_lua(agent):
    agent = adapt_agent_actions(agent)

    lines = [
        "-- Auto-generated by evolution_loop_upright_v18.py",
        "TORIBASHAI_AGENT = {}",
        f'TORIBASHAI_AGENT.name = "{agent["name"]}"',
        "TORIBASHAI_AGENT.control_joints = { "
        + ", ".join(str(j) for j in agent["control_joints"])
        + " }",
        "TORIBASHAI_AGENT.actions = {",
    ]

    for action in agent["actions"]:
        lines.append("    { " + ", ".join(str(int(v)) for v in action) + " },")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")
    AGENT_LUA.write_text("\n".join(lines), encoding="utf-8")


def reset_toribash():
    try:
        subprocess.run(["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"], check=False)
        time.sleep(0.10)

        try:
            p = subprocess.Popen(["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE)
            p.communicate(RESET_COMMAND.encode("utf-8"))

            subprocess.run(["xdotool", "key", "t"], check=False)
            time.sleep(0.08)
            subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
            time.sleep(0.03)
            subprocess.run(["xdotool", "key", "BackSpace"], check=False)
            time.sleep(0.03)
            subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
            time.sleep(0.03)
            subprocess.run(["xdotool", "key", "Return"], check=False)
        except Exception:
            subprocess.run(["xdotool", "key", "t"], check=False)
            time.sleep(0.08)
            subprocess.run(["xdotool", "type", "--delay", "1", RESET_COMMAND], check=False)
            subprocess.run(["xdotool", "key", "Return"], check=False)

        print("Reset envoyé:", RESET_COMMAND)
    except Exception as e:
        print("Reset erreur:", e)


def wait_result(timeout=90):
    start = time.time()
    while time.time() - start < timeout:
        if RESULT_PATH.exists():
            try:
                result = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return result
            except Exception:
                pass
        time.sleep(0.25)

    return {"score": -999999, "reason": "timeout", "fell": True, "frames": 0}


def mutation_rate_for_action(action_index):
    if action_index < EARLY_ACTIONS_PROTECTED:
        return BASE_MUTATION_RATE * EARLY_MUTATION_FACTOR
    return BASE_MUTATION_RATE


def choose_mutation_value(current):
    if random.random() < NO_CHANGE_BIAS:
        return 0
    choices = [v for v in JOINT_VALUES if v != int(current)]
    return random.choice(choices)


def mutate(agent):
    child = adapt_agent_actions(agent)
    mutations = 0
    no_change_mutations = 0
    early_mutations = 0

    for action_index, action in enumerate(child["actions"]):
        rate = mutation_rate_for_action(action_index)

        for i in range(len(action)):
            if random.random() < rate:
                current = int(action[i])
                new_value = choose_mutation_value(current)
                action[i] = new_value
                mutations += 1

                if new_value == 0:
                    no_change_mutations += 1
                if action_index < EARLY_ACTIONS_PROTECTED:
                    early_mutations += 1

    child["mutations"] = mutations
    child["no_change_mutations"] = no_change_mutations
    child["early_mutations"] = early_mutations
    child["mutation_rate"] = BASE_MUTATION_RATE
    child["mutation_strategy"] = "v18_balance_detected_stillness"
    return child


def evaluate(agent, gen, idx):
    agent = adapt_agent_actions(agent)
    agent["name"] = f"upright_v18_gen_{gen:05d}_agent_{idx:03d}"

    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_lua(agent)

    print("Exported:", AGENT_LUA)
    print("Source:", path)
    print("Agent:", agent["name"])
    print("Mutations:", agent.get("mutations", 0))
    print("No-change mutations:", agent.get("no_change_mutations", 0))
    print("Early mutations:", agent.get("early_mutations", 0))

    reset_toribash()
    print("Attente :", RESULT_PATH)

    result = wait_result()
    score = float(result.get("score", -999999))

    result_path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json"
    save_json(result_path, result)

    return score, result, path


def main():
    POP_DIR.mkdir(parents=True, exist_ok=True)
    BEST_DIR.mkdir(parents=True, exist_ok=True)
    ensure_seed()

    if CHAMPION_AGENT.exists():
        champion = adapt_agent_actions(load_json(CHAMPION_AGENT))
        save_json(CHAMPION_AGENT, champion)
        print("Champion V18 chargé:", CHAMPION_AGENT)
    else:
        champion = adapt_agent_actions(load_json(SEED_AGENT))
        save_json(CHAMPION_AGENT, champion)
        print("Champion V18 initialisé depuis seed:", SEED_AGENT)

    champion_score = -999999

    print()
    print("=" * 49)
    print("INIT MANUEL TORIBASH")
    print("=" * 49)
    print("Dans Toribash lance :")
    print("/lm ToribashAI/toribashai_goal_flat_v1.tbm")
    print("/ls toribash_upright_runner_v18.lua")
    input("\nQuand c'est prêt, appuie Entrée ici... ")

    for gen in range(GENERATIONS):
        print()
        print("=" * 49)
        print(f"GENERATION {gen}")
        print("=" * 49)

        candidates = []
        for i in range(POP_SIZE):
            if i == 0:
                candidate = adapt_agent_actions(champion)
                candidate["mutations"] = 0
                candidate["elite_copy"] = True
            else:
                candidate = mutate(champion)
                candidate["elite_copy"] = False
            candidates.append(candidate)

        best_score = -999999
        best_path = None
        best_result = None

        for i, candidate in enumerate(candidates):
            print()
            print("=" * 49)
            print(f"GEN {gen} | CANDIDAT {i:03d}")
            print("=" * 49)

            score, result, path = evaluate(candidate, gen, i)
            print("SCORE =", score)
            print(result)

            if score > best_score:
                best_score = score
                best_path = path
                best_result = result

        print()
        print("=" * 49)
        print("MEILLEUR CANDIDAT")
        print("=" * 49)
        print("Score:", best_score)
        print("Fichier:", best_path)
        print("Résultat:", best_result)

        if best_score > champion_score:
            champion_score = best_score
            champion = adapt_agent_actions(load_json(best_path))
            champion_save = BEST_DIR / f"champion_gen_{gen:05d}_score_{champion_score:.2f}.json"
            save_json(champion_save, champion)
            shutil.copy(champion_save, CHAMPION_AGENT)
            print("NOUVEAU CHAMPION:", champion_save)
        else:
            print("Pas mieux que le champion actuel")

        save_json(
            ROOT / "evolution/upright_v18_state.json",
            {
                "generation": gen,
                "champion_score": champion_score,
                "champion_path": str(CHAMPION_AGENT),
                "best_score_this_gen": best_score,
                "best_result_this_gen": best_result,
                "mutation_rate": BASE_MUTATION_RATE,
                "mutation_strategy": "v18_balance_detected_stillness",
                "mod": "ToribashAI/toribashai_goal_flat_v1.tbm",
                "frames_per_action": 20,
                "max_frames": 500,
                "target_actions": TARGET_ACTIONS,
            },
        )


if __name__ == "__main__":
    main()
