#!/usr/bin/env python3
import copy
import json
import random
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path.home() / "Documents" / "ToribashAI"

SEED_AGENT = ROOT / "evolution/recovery_seed_v1.json"
CHAMPION_AGENT = ROOT / "evolution/recovery_champion_v1.json"

TORIBASH_SCRIPT_DIR = (
    Path.home()
    / ".var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Toribash/data/script"
)

AGENT_LUA = TORIBASH_SCRIPT_DIR / "toribashai_agent_current.lua"
RESULT_PATH = TORIBASH_SCRIPT_DIR / "toribashai_episode_result.json"

POP_DIR = ROOT / "evolution/population_recovery_v1"
BEST_DIR = ROOT / "evolution/best_recovery_v1"

POP_SIZE = 12
GENERATIONS = 999999

MUTATION_RATE = 0.04
JOINT_VALUES = [1, 2, 3, 4]

RESET_COMMAND = "/reset"


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2), encoding="utf-8")


def export_lua(agent):
    lines = []
    lines.append("-- Auto-generated by evolution_loop_recovery_v1.py")
    lines.append("TORIBASHAI_AGENT = {}")
    lines.append(f'TORIBASHAI_AGENT.name = "{agent["name"]}"')
    lines.append(
        "TORIBASHAI_AGENT.control_joints = { "
        + ", ".join(str(j) for j in agent["control_joints"])
        + " }"
    )
    lines.append("TORIBASHAI_AGENT.actions = {")

    for action in agent["actions"]:
        lines.append("    { " + ", ".join(str(int(v)) for v in action) + " },")

    lines.append("}")
    lines.append("return TORIBASHAI_AGENT")

    AGENT_LUA.write_text("\n".join(lines), encoding="utf-8")


def reset_toribash():
    try:
        subprocess.run(
            ["xdotool", "search", "--name", "Toribash", "windowactivate", "--sync"],
            check=False,
        )
        time.sleep(0.10)

        # xclip évite wl-copy si absent
        p = subprocess.Popen(["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE)
        p.communicate(RESET_COMMAND.encode("utf-8"))

        subprocess.run(["xdotool", "key", "t"], check=False)
        time.sleep(0.08)
        subprocess.run(["xdotool", "key", "ctrl+a"], check=False)
        time.sleep(0.03)
        subprocess.run(["xdotool", "key", "BackSpace"], check=False)
        time.sleep(0.03)
        subprocess.run(["xdotool", "key", "ctrl+v"], check=False)
        time.sleep(0.03)
        subprocess.run(["xdotool", "key", "Return"], check=False)

        print("Reset envoyé")
    except Exception as e:
        print("Reset erreur:", e)


def wait_result(timeout=45):
    start = time.time()

    while time.time() - start < timeout:
        if RESULT_PATH.exists():
            try:
                result = load_json(RESULT_PATH)
                RESULT_PATH.unlink(missing_ok=True)
                return result
            except Exception:
                pass

        time.sleep(0.25)

    return {
        "score": -999999,
        "reason": "timeout",
        "fell": True,
        "frames": 0,
        "posture_z": 0,
        "drift": 999,
    }


def mutate(agent):
    child = copy.deepcopy(agent)
    mutations = 0

    for action in child["actions"]:
        for i in range(len(action)):
            if random.random() < MUTATION_RATE:
                current = int(action[i])
                choices = [v for v in JOINT_VALUES if v != current]
                action[i] = random.choice(choices)
                mutations += 1

    child["mutations"] = mutations
    child["mutation_rate"] = MUTATION_RATE
    return child


def evaluate(agent, gen, idx):
    agent = copy.deepcopy(agent)
    agent["name"] = f"recovery_v1_gen_{gen:05d}_agent_{idx:03d}"

    path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}.json"
    save_json(path, agent)
    export_lua(agent)

    print("Exported:", AGENT_LUA)
    print("Source:", path)
    print("Agent:", agent["name"])
    print("Mutations:", agent.get("mutations", 0))

    reset_toribash()
    print("Attente :", RESULT_PATH)

    result = wait_result()
    score = float(result.get("score", -999999))

    result_path = POP_DIR / f"gen_{gen:05d}_agent_{idx:03d}_result.json"
    save_json(result_path, result)

    return score, result, path


def main():
    POP_DIR.mkdir(parents=True, exist_ok=True)
    BEST_DIR.mkdir(parents=True, exist_ok=True)

    if CHAMPION_AGENT.exists():
        champion = load_json(CHAMPION_AGENT)
        print("Champion chargé:", CHAMPION_AGENT)
    else:
        champion = load_json(SEED_AGENT)
        save_json(CHAMPION_AGENT, champion)
        print("Seed chargé:", SEED_AGENT)

    champion_score = -999999

    print()
    print("=" * 49)
    print("INIT MANUEL TORIBASH")
    print("=" * 49)
    print("Dans Toribash lance :")
    print("/lm toribashai_goal_flat_v1.tbm")
    print("/ls toribash_recovery_runner_v1.lua")
    input("\nQuand c'est prêt, appuie Entrée ici... ")

    for gen in range(GENERATIONS):
        print()
        print("=" * 49)
        print(f"GENERATION {gen}")
        print("=" * 49)

        candidates = []

        for i in range(POP_SIZE):
            if i == 0:
                candidate = copy.deepcopy(champion)
                candidate["mutations"] = 0
                candidate["elite_copy"] = True
            else:
                candidate = mutate(champion)
                candidate["elite_copy"] = False

            candidates.append(candidate)

        best_score = -999999
        best_path = None
        best_result = None

        for i, candidate in enumerate(candidates):
            print()
            print("=" * 49)
            print(f"GEN {gen} | CANDIDAT {i:03d}")
            print("=" * 49)

            score, result, path = evaluate(candidate, gen, i)

            print("SCORE =", score)
            print(result)

            if score > best_score:
                best_score = score
                best_path = path
                best_result = result

        print()
        print("=" * 49)
        print("MEILLEUR CANDIDAT")
        print("=" * 49)
        print("Score:", best_score)
        print("Fichier:", best_path)
        print("Résultat:", best_result)

        if best_score > champion_score:
            champion_score = best_score
            champion = load_json(best_path)

            champion_save = BEST_DIR / f"champion_gen_{gen:05d}_score_{champion_score:.2f}.json"
            save_json(champion_save, champion)
            shutil.copy(champion_save, CHAMPION_AGENT)

            print("NOUVEAU CHAMPION:", champion_save)
        else:
            print("Pas mieux que le champion actuel")

        save_json(
            ROOT / "evolution/recovery_v1_state.json",
            {
                "generation": gen,
                "champion_score": champion_score,
                "champion_path": str(CHAMPION_AGENT),
                "best_score_this_gen": best_score,
                "best_result_this_gen": best_result,
                "mutation_rate": MUTATION_RATE,
            },
        )


if __name__ == "__main__":
    main()
